//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for CustomerOrder complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="CustomerOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderHeader" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}OrderHeader" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "CustomerOrder",
    propOrder = {"orderHeader"})
@XmlSeeAlso({
  com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
      .UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.class,
  com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
      .UpdateFulfillmentOrderResponse.MessageBody.CustomerOrder.class
})
public class CustomerOrder {

  protected OrderHeader orderHeader;

  /**
   * Gets the value of the orderHeader property.
   *
   * @return possible object is {@link OrderHeader }
   */
  public OrderHeader getOrderHeader() {
    return orderHeader;
  }

  /**
   * Sets the value of the orderHeader property.
   *
   * @param value allowed object is {@link OrderHeader }
   */
  public void setOrderHeader(OrderHeader value) {
    this.orderHeader = value;
  }
}
