//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Java class for DeliveryDetails complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DeliveryDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="deliveryETA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="deliveryScheduleTimeSlot" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}TimeRange" minOccurs="0"/>
 *         &lt;element name="deliveryInstructions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha512" minOccurs="0"/>
 *         &lt;element name="doorstepTime" type="{http://www.w3.org/2001/XMLSchema}time" minOccurs="0"/>
 *         &lt;element name="deliveryZone" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha20" minOccurs="0"/>
 *         &lt;element name="deliveryLocation" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Location" minOccurs="0"/>
 *         &lt;element name="deliveryContact" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DeliveryContact" minOccurs="0"/>
 *         &lt;element name="carrierMethodCode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha10" minOccurs="0"/>
 *         &lt;element name="shippingMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}ShippingMethod" minOccurs="0"/>
 *         &lt;element name="vehicleRegistrationNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha20" minOccurs="0"/>
 *         &lt;element name="carrierMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CarrierMethod" minOccurs="0"/>
 *         &lt;element name="deliveryNoteOrderMessage" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Message" minOccurs="0"/>
 *         &lt;element name="deliveryNoteMarketingMessage" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Message" minOccurs="0"/>
 *         &lt;element name="deliveryNoteReturnInstructions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Message" minOccurs="0"/>
 *         &lt;element name="shipETA" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "DeliveryDetails",
    propOrder = {
      "deliveryETA",
      "deliveryScheduleTimeSlot",
      "deliveryInstructions",
      "doorstepTime",
      "deliveryZone",
      "deliveryLocation",
      "deliveryContact",
      "carrierMethodCode",
      "shippingMethod",
      "vehicleRegistrationNumber",
      "carrierMethod",
      "deliveryNoteOrderMessage",
      "deliveryNoteMarketingMessage",
      "deliveryNoteReturnInstructions",
      "shipETA"
    })
public class DeliveryDetails {

  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar deliveryETA;

  protected TimeRange deliveryScheduleTimeSlot;
  protected String deliveryInstructions;

  @XmlSchemaType(name = "time")
  protected XMLGregorianCalendar doorstepTime;

  protected String deliveryZone;
  protected Location deliveryLocation;
  protected DeliveryContact deliveryContact;
  protected String carrierMethodCode;
  protected ShippingMethod shippingMethod;
  protected String vehicleRegistrationNumber;
  protected CarrierMethod carrierMethod;
  protected Message deliveryNoteOrderMessage;
  protected Message deliveryNoteMarketingMessage;
  protected Message deliveryNoteReturnInstructions;

  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar shipETA;

  /**
   * Gets the value of the deliveryETA property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDeliveryETA() {
    return deliveryETA;
  }

  /**
   * Sets the value of the deliveryETA property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setDeliveryETA(XMLGregorianCalendar value) {
    this.deliveryETA = value;
  }

  /**
   * Gets the value of the deliveryScheduleTimeSlot property.
   *
   * @return possible object is {@link TimeRange }
   */
  public TimeRange getDeliveryScheduleTimeSlot() {
    return deliveryScheduleTimeSlot;
  }

  /**
   * Sets the value of the deliveryScheduleTimeSlot property.
   *
   * @param value allowed object is {@link TimeRange }
   */
  public void setDeliveryScheduleTimeSlot(TimeRange value) {
    this.deliveryScheduleTimeSlot = value;
  }

  /**
   * Gets the value of the deliveryInstructions property.
   *
   * @return possible object is {@link String }
   */
  public String getDeliveryInstructions() {
    return deliveryInstructions;
  }

  /**
   * Sets the value of the deliveryInstructions property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDeliveryInstructions(String value) {
    this.deliveryInstructions = value;
  }

  /**
   * Gets the value of the doorstepTime property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDoorstepTime() {
    return doorstepTime;
  }

  /**
   * Sets the value of the doorstepTime property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setDoorstepTime(XMLGregorianCalendar value) {
    this.doorstepTime = value;
  }

  /**
   * Gets the value of the deliveryZone property.
   *
   * @return possible object is {@link String }
   */
  public String getDeliveryZone() {
    return deliveryZone;
  }

  /**
   * Sets the value of the deliveryZone property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDeliveryZone(String value) {
    this.deliveryZone = value;
  }

  /**
   * Gets the value of the deliveryLocation property.
   *
   * @return possible object is {@link Location }
   */
  public Location getDeliveryLocation() {
    return deliveryLocation;
  }

  /**
   * Sets the value of the deliveryLocation property.
   *
   * @param value allowed object is {@link Location }
   */
  public void setDeliveryLocation(Location value) {
    this.deliveryLocation = value;
  }

  /**
   * Gets the value of the deliveryContact property.
   *
   * @return possible object is {@link DeliveryContact }
   */
  public DeliveryContact getDeliveryContact() {
    return deliveryContact;
  }

  /**
   * Sets the value of the deliveryContact property.
   *
   * @param value allowed object is {@link DeliveryContact }
   */
  public void setDeliveryContact(DeliveryContact value) {
    this.deliveryContact = value;
  }

  /**
   * Gets the value of the carrierMethodCode property.
   *
   * @return possible object is {@link String }
   */
  public String getCarrierMethodCode() {
    return carrierMethodCode;
  }

  /**
   * Sets the value of the carrierMethodCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCarrierMethodCode(String value) {
    this.carrierMethodCode = value;
  }

  /**
   * Gets the value of the shippingMethod property.
   *
   * @return possible object is {@link ShippingMethod }
   */
  public ShippingMethod getShippingMethod() {
    return shippingMethod;
  }

  /**
   * Sets the value of the shippingMethod property.
   *
   * @param value allowed object is {@link ShippingMethod }
   */
  public void setShippingMethod(ShippingMethod value) {
    this.shippingMethod = value;
  }

  /**
   * Gets the value of the vehicleRegistrationNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getVehicleRegistrationNumber() {
    return vehicleRegistrationNumber;
  }

  /**
   * Sets the value of the vehicleRegistrationNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setVehicleRegistrationNumber(String value) {
    this.vehicleRegistrationNumber = value;
  }

  /**
   * Gets the value of the carrierMethod property.
   *
   * @return possible object is {@link CarrierMethod }
   */
  public CarrierMethod getCarrierMethod() {
    return carrierMethod;
  }

  /**
   * Sets the value of the carrierMethod property.
   *
   * @param value allowed object is {@link CarrierMethod }
   */
  public void setCarrierMethod(CarrierMethod value) {
    this.carrierMethod = value;
  }

  /**
   * Gets the value of the deliveryNoteOrderMessage property.
   *
   * @return possible object is {@link Message }
   */
  public Message getDeliveryNoteOrderMessage() {
    return deliveryNoteOrderMessage;
  }

  /**
   * Sets the value of the deliveryNoteOrderMessage property.
   *
   * @param value allowed object is {@link Message }
   */
  public void setDeliveryNoteOrderMessage(Message value) {
    this.deliveryNoteOrderMessage = value;
  }

  /**
   * Gets the value of the deliveryNoteMarketingMessage property.
   *
   * @return possible object is {@link Message }
   */
  public Message getDeliveryNoteMarketingMessage() {
    return deliveryNoteMarketingMessage;
  }

  /**
   * Sets the value of the deliveryNoteMarketingMessage property.
   *
   * @param value allowed object is {@link Message }
   */
  public void setDeliveryNoteMarketingMessage(Message value) {
    this.deliveryNoteMarketingMessage = value;
  }

  /**
   * Gets the value of the deliveryNoteReturnInstructions property.
   *
   * @return possible object is {@link Message }
   */
  public Message getDeliveryNoteReturnInstructions() {
    return deliveryNoteReturnInstructions;
  }

  /**
   * Sets the value of the deliveryNoteReturnInstructions property.
   *
   * @param value allowed object is {@link Message }
   */
  public void setDeliveryNoteReturnInstructions(Message value) {
    this.deliveryNoteReturnInstructions = value;
  }

  /**
   * Gets the value of the shipETA property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getShipETA() {
    return shipETA;
  }

  /**
   * Sets the value of the shipETA property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setShipETA(XMLGregorianCalendar value) {
    this.shipETA = value;
  }
}
