//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for MessageFault complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MessageFault">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ErrorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ErrorNode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ErrorText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ErrorDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "MessageFault",
    namespace = "http://www.xmlns.walmartstores.com/Fault/datatypes/MessageFault/1.0/",
    propOrder = {"errorCode", "errorNode", "errorText", "errorDescription"})
public class MessageFault {

  @XmlElement(name = "ErrorCode", required = true)
  protected String errorCode;

  @XmlElement(name = "ErrorNode")
  protected String errorNode;

  @XmlElement(name = "ErrorText", required = true)
  protected String errorText;

  @XmlElement(name = "ErrorDescription")
  protected String errorDescription;

  /**
   * Gets the value of the errorCode property.
   *
   * @return possible object is {@link String }
   */
  public String getErrorCode() {
    return errorCode;
  }

  /**
   * Sets the value of the errorCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setErrorCode(String value) {
    this.errorCode = value;
  }

  /**
   * Gets the value of the errorNode property.
   *
   * @return possible object is {@link String }
   */
  public String getErrorNode() {
    return errorNode;
  }

  /**
   * Sets the value of the errorNode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setErrorNode(String value) {
    this.errorNode = value;
  }

  /**
   * Gets the value of the errorText property.
   *
   * @return possible object is {@link String }
   */
  public String getErrorText() {
    return errorText;
  }

  /**
   * Sets the value of the errorText property.
   *
   * @param value allowed object is {@link String }
   */
  public void setErrorText(String value) {
    this.errorText = value;
  }

  /**
   * Gets the value of the errorDescription property.
   *
   * @return possible object is {@link String }
   */
  public String getErrorDescription() {
    return errorDescription;
  }

  /**
   * Sets the value of the errorDescription property.
   *
   * @param value allowed object is {@link String }
   */
  public void setErrorDescription(String value) {
    this.errorDescription = value;
  }
}
