//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Offering complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Offering">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="isAvailableForPickup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha512" minOccurs="0"/>
 *         &lt;element name="globalTradeItem" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}GlobalTradeItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="price" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Price">
 *                 &lt;sequence>
 *                   &lt;element name="priceAdjustment" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PriceAdjustment" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="tax" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Tax" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha20" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Offering",
    propOrder = {
      "isAvailableForPickup",
      "id",
      "description",
      "globalTradeItem",
      "price",
      "tax",
      "type"
    })
@XmlSeeAlso({
  com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.Product.class,
  com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.OrderLine
      .SubstitutionLine.Product.class
})
public class Offering {

  protected Boolean isAvailableForPickup;

  @XmlSchemaType(name = "unsignedInt")
  protected Long id;

  protected String description;
  protected List<GlobalTradeItem> globalTradeItem;
  protected Offering.Price price;
  protected List<Tax> tax;
  protected String type;

  /**
   * Gets the value of the isAvailableForPickup property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsAvailableForPickup() {
    return isAvailableForPickup;
  }

  /**
   * Sets the value of the isAvailableForPickup property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsAvailableForPickup(Boolean value) {
    this.isAvailableForPickup = value;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link Long }
   */
  public Long getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link Long }
   */
  public void setId(Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the globalTradeItem property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the globalTradeItem property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getGlobalTradeItem().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link GlobalTradeItem }
   */
  public List<GlobalTradeItem> getGlobalTradeItem() {
    if (globalTradeItem == null) {
      globalTradeItem = new ArrayList<>();
    }
    return this.globalTradeItem;
  }

  /**
   * Gets the value of the price property.
   *
   * @return possible object is {@link Offering.Price }
   */
  public Offering.Price getPrice() {
    return price;
  }

  /**
   * Sets the value of the price property.
   *
   * @param value allowed object is {@link Offering.Price }
   */
  public void setPrice(Offering.Price value) {
    this.price = value;
  }

  /**
   * Gets the value of the tax property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the tax property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTax().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Tax }
   */
  public List<Tax> getTax() {
    if (tax == null) {
      tax = new ArrayList<>();
    }
    return this.tax;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  public void setGlobalTradeItem(List<GlobalTradeItem> value) {
    this.globalTradeItem = null;
    List<GlobalTradeItem> draftl = this.getGlobalTradeItem();
    draftl.addAll(value);
  }

  public void setTax(List<Tax> value) {
    this.tax = null;
    List<Tax> draftl = this.getTax();
    draftl.addAll(value);
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Price">
   *       &lt;sequence>
   *         &lt;element name="priceAdjustment" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PriceAdjustment" maxOccurs="unbounded" minOccurs="0"/>
   *       &lt;/sequence>
   *     &lt;/extension>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"priceAdjustment"})
  public static class Price
      extends com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
          .Price {

    protected List<PriceAdjustment> priceAdjustment;

    /**
     * Gets the value of the priceAdjustment property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the priceAdjustment property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getPriceAdjustment().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link PriceAdjustment }
     */
    public List<PriceAdjustment> getPriceAdjustment() {
      if (priceAdjustment == null) {
        priceAdjustment = new ArrayList<>();
      }
      return this.priceAdjustment;
    }

    public void setPriceAdjustment(List<PriceAdjustment> value) {
      this.priceAdjustment = null;
      List<PriceAdjustment> draftl = this.getPriceAdjustment();
      draftl.addAll(value);
    }
  }
}
