//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for OrderLine complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OrderLine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lineNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Status" minOccurs="0"/>
 *         &lt;element name="product" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Product" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="price" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Price">
 *                 &lt;sequence>
 *                   &lt;element name="priceAdjustment" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PriceAdjustment" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="orderLineQuantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
 *         &lt;element name="totalWeight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Weight" minOccurs="0"/>
 *         &lt;element name="isSubstitutionAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="pickingInstructions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PickingInstructions" minOccurs="0"/>
 *         &lt;element name="isOrderByQuantity" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="totalTaxAmount" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Amount" minOccurs="0"/>
 *         &lt;element name="fulfilledUnitPrice" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Price" minOccurs="0"/>
 *         &lt;element name="substitutionLine" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}SubstitutionLine">
 *                 &lt;sequence>
 *                   &lt;element name="product" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Offering">
 *                           &lt;sequence>
 *                             &lt;element name="weight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Weight" minOccurs="0"/>
 *                             &lt;element name="sellingQuantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="pickedQuantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
 *         &lt;element name="substitutedQuantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "OrderLine",
    propOrder = {
      "lineNumber",
      "status",
      "product",
      "price",
      "orderLineQuantity",
      "totalWeight",
      "isSubstitutionAllowed",
      "pickingInstructions",
      "isOrderByQuantity",
      "totalTaxAmount",
      "fulfilledUnitPrice",
      "substitutionLine",
      "pickedQuantity",
      "substitutedQuantity"
    })
@XmlSeeAlso({
  com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
      .UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.OrderLines.class,
  com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
      .UpdateFulfillmentOrderResponse.MessageBody.CustomerOrder.FulfillmentOrder.OrderLines.class
})
public class OrderLine {

  @XmlSchemaType(name = "unsignedInt")
  protected Long lineNumber;

  protected Status status;
  protected List<
          com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
              .Product>
      product;
  protected OrderLine.Price price;
  protected Quantity orderLineQuantity;
  protected Weight totalWeight;
  protected Boolean isSubstitutionAllowed;
  protected PickingInstructions pickingInstructions;
  protected Boolean isOrderByQuantity;
  protected Amount totalTaxAmount;
  protected com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
          .Price
      fulfilledUnitPrice;
  protected List<OrderLine.SubstitutionLine> substitutionLine;
  protected Quantity pickedQuantity;
  protected Quantity substitutedQuantity;

  /**
   * Gets the value of the lineNumber property.
   *
   * @return possible object is {@link Long }
   */
  public Long getLineNumber() {
    return lineNumber;
  }

  /**
   * Sets the value of the lineNumber property.
   *
   * @param value allowed object is {@link Long }
   */
  public void setLineNumber(Long value) {
    this.lineNumber = value;
  }

  /**
   * Gets the value of the status property.
   *
   * @return possible object is {@link Status }
   */
  public Status getStatus() {
    return status;
  }

  /**
   * Sets the value of the status property.
   *
   * @param value allowed object is {@link Status }
   */
  public void setStatus(Status value) {
    this.status = value;
  }

  /**
   * Gets the value of the product property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the product property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getProduct().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link
   * com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.Product }
   */
  public List<
          com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
              .Product>
      getProduct() {
    if (product == null) {
      product = new ArrayList<>();
    }
    return this.product;
  }

  /**
   * Gets the value of the price property.
   *
   * @return possible object is {@link OrderLine.Price }
   */
  public OrderLine.Price getPrice() {
    return price;
  }

  /**
   * Sets the value of the price property.
   *
   * @param value allowed object is {@link OrderLine.Price }
   */
  public void setPrice(OrderLine.Price value) {
    this.price = value;
  }

  /**
   * Gets the value of the orderLineQuantity property.
   *
   * @return possible object is {@link Quantity }
   */
  public Quantity getOrderLineQuantity() {
    return orderLineQuantity;
  }

  /**
   * Sets the value of the orderLineQuantity property.
   *
   * @param value allowed object is {@link Quantity }
   */
  public void setOrderLineQuantity(Quantity value) {
    this.orderLineQuantity = value;
  }

  /**
   * Gets the value of the totalWeight property.
   *
   * @return possible object is {@link Weight }
   */
  public Weight getTotalWeight() {
    return totalWeight;
  }

  /**
   * Sets the value of the totalWeight property.
   *
   * @param value allowed object is {@link Weight }
   */
  public void setTotalWeight(Weight value) {
    this.totalWeight = value;
  }

  /**
   * Gets the value of the isSubstitutionAllowed property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsSubstitutionAllowed() {
    return isSubstitutionAllowed;
  }

  /**
   * Sets the value of the isSubstitutionAllowed property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsSubstitutionAllowed(Boolean value) {
    this.isSubstitutionAllowed = value;
  }

  /**
   * Gets the value of the pickingInstructions property.
   *
   * @return possible object is {@link PickingInstructions }
   */
  public PickingInstructions getPickingInstructions() {
    return pickingInstructions;
  }

  /**
   * Sets the value of the pickingInstructions property.
   *
   * @param value allowed object is {@link PickingInstructions }
   */
  public void setPickingInstructions(PickingInstructions value) {
    this.pickingInstructions = value;
  }

  /**
   * Gets the value of the isOrderByQuantity property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsOrderByQuantity() {
    return isOrderByQuantity;
  }

  /**
   * Sets the value of the isOrderByQuantity property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsOrderByQuantity(Boolean value) {
    this.isOrderByQuantity = value;
  }

  /**
   * Gets the value of the totalTaxAmount property.
   *
   * @return possible object is {@link Amount }
   */
  public Amount getTotalTaxAmount() {
    return totalTaxAmount;
  }

  /**
   * Sets the value of the totalTaxAmount property.
   *
   * @param value allowed object is {@link Amount }
   */
  public void setTotalTaxAmount(Amount value) {
    this.totalTaxAmount = value;
  }

  /**
   * Gets the value of the fulfilledUnitPrice property.
   *
   * @return possible object is {@link
   *     com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.Price }
   */
  public com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.Price
      getFulfilledUnitPrice() {
    return fulfilledUnitPrice;
  }

  /**
   * Sets the value of the fulfilledUnitPrice property.
   *
   * @param value allowed object is {@link
   *     com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.Price }
   */
  public void setFulfilledUnitPrice(
      com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.Price
          value) {
    this.fulfilledUnitPrice = value;
  }

  /**
   * Gets the value of the substitutionLine property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the substitutionLine property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getSubstitutionLine().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link OrderLine.SubstitutionLine }
   */
  public List<OrderLine.SubstitutionLine> getSubstitutionLine() {
    if (substitutionLine == null) {
      substitutionLine = new ArrayList<>();
    }
    return this.substitutionLine;
  }

  /**
   * Gets the value of the pickedQuantity property.
   *
   * @return possible object is {@link Quantity }
   */
  public Quantity getPickedQuantity() {
    return pickedQuantity;
  }

  /**
   * Sets the value of the pickedQuantity property.
   *
   * @param value allowed object is {@link Quantity }
   */
  public void setPickedQuantity(Quantity value) {
    this.pickedQuantity = value;
  }

  /**
   * Gets the value of the substitutedQuantity property.
   *
   * @return possible object is {@link Quantity }
   */
  public Quantity getSubstitutedQuantity() {
    return substitutedQuantity;
  }

  /**
   * Sets the value of the substitutedQuantity property.
   *
   * @param value allowed object is {@link Quantity }
   */
  public void setSubstitutedQuantity(Quantity value) {
    this.substitutedQuantity = value;
  }

  public void setProduct(
      List<
              com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
                  .Product>
          value) {
    this.product = null;
    List<
            com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
                .Product>
        draftl = this.getProduct();
    draftl.addAll(value);
  }

  public void setSubstitutionLine(List<OrderLine.SubstitutionLine> value) {
    this.substitutionLine = null;
    List<OrderLine.SubstitutionLine> draftl = this.getSubstitutionLine();
    draftl.addAll(value);
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Price">
   *       &lt;sequence>
   *         &lt;element name="priceAdjustment" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PriceAdjustment" maxOccurs="unbounded" minOccurs="0"/>
   *       &lt;/sequence>
   *     &lt;/extension>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"priceAdjustment"})
  public static class Price
      extends com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
          .Price {

    protected List<PriceAdjustment> priceAdjustment;

    /**
     * Gets the value of the priceAdjustment property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the priceAdjustment property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getPriceAdjustment().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link PriceAdjustment }
     */
    public List<PriceAdjustment> getPriceAdjustment() {
      if (priceAdjustment == null) {
        priceAdjustment = new ArrayList<>();
      }
      return this.priceAdjustment;
    }

    public void setPriceAdjustment(List<PriceAdjustment> value) {
      this.priceAdjustment = null;
      List<PriceAdjustment> draftl = this.getPriceAdjustment();
      draftl.addAll(value);
    }
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}SubstitutionLine">
   *       &lt;sequence>
   *         &lt;element name="product" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Offering">
   *                 &lt;sequence>
   *                   &lt;element name="weight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Weight" minOccurs="0"/>
   *                   &lt;element name="sellingQuantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
   *                 &lt;/sequence>
   *               &lt;/extension>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *     &lt;/extension>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"product"})
  public static class SubstitutionLine
      extends com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
          .SubstitutionLine {

    protected List<OrderLine.SubstitutionLine.Product> product;

    /**
     * Gets the value of the product property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the product property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link
     * OrderLine.SubstitutionLine.Product }
     */
    public List<OrderLine.SubstitutionLine.Product> getProduct() {
      if (product == null) {
        product = new ArrayList<>();
      }
      return this.product;
    }

    public void setProduct(List<OrderLine.SubstitutionLine.Product> value) {
      this.product = null;
      List<OrderLine.SubstitutionLine.Product> draftl = this.getProduct();
      draftl.addAll(value);
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Offering">
     *       &lt;sequence>
     *         &lt;element name="weight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Weight" minOccurs="0"/>
     *         &lt;element name="sellingQuantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {"weight", "sellingQuantity"})
    public static class Product extends Offering {

      protected Weight weight;
      protected Quantity sellingQuantity;

      /**
       * Gets the value of the weight property.
       *
       * @return possible object is {@link Weight }
       */
      public Weight getWeight() {
        return weight;
      }

      /**
       * Sets the value of the weight property.
       *
       * @param value allowed object is {@link Weight }
       */
      public void setWeight(Weight value) {
        this.weight = value;
      }

      /**
       * Gets the value of the sellingQuantity property.
       *
       * @return possible object is {@link Quantity }
       */
      public Quantity getSellingQuantity() {
        return sellingQuantity;
      }

      /**
       * Sets the value of the sellingQuantity property.
       *
       * @param value allowed object is {@link Quantity }
       */
      public void setSellingQuantity(Quantity value) {
        this.sellingQuantity = value;
      }
    }
  }
}
