//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for PaymentInstrument complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PaymentInstrument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="referenceNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha10" minOccurs="0"/>
 *         &lt;element name="instrumentType" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PaymentInstrumentType" minOccurs="0"/>
 *         &lt;element name="holderName" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="issuer" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Issuer" minOccurs="0"/>
 *         &lt;element name="suffixNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha10" minOccurs="0"/>
 *         &lt;element name="issuerCountryCode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha2" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "PaymentInstrument",
    propOrder = {
      "referenceNumber",
      "instrumentType",
      "holderName",
      "issuer",
      "suffixNumber",
      "issuerCountryCode"
    })
@XmlSeeAlso({PaymentCard.class})
public class PaymentInstrument {

  protected String referenceNumber;
  protected PaymentInstrumentType instrumentType;
  protected String holderName;
  protected Issuer issuer;
  protected String suffixNumber;
  protected String issuerCountryCode;

  /**
   * Gets the value of the referenceNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getReferenceNumber() {
    return referenceNumber;
  }

  /**
   * Sets the value of the referenceNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReferenceNumber(String value) {
    this.referenceNumber = value;
  }

  /**
   * Gets the value of the instrumentType property.
   *
   * @return possible object is {@link PaymentInstrumentType }
   */
  public PaymentInstrumentType getInstrumentType() {
    return instrumentType;
  }

  /**
   * Sets the value of the instrumentType property.
   *
   * @param value allowed object is {@link PaymentInstrumentType }
   */
  public void setInstrumentType(PaymentInstrumentType value) {
    this.instrumentType = value;
  }

  /**
   * Gets the value of the holderName property.
   *
   * @return possible object is {@link String }
   */
  public String getHolderName() {
    return holderName;
  }

  /**
   * Sets the value of the holderName property.
   *
   * @param value allowed object is {@link String }
   */
  public void setHolderName(String value) {
    this.holderName = value;
  }

  /**
   * Gets the value of the issuer property.
   *
   * @return possible object is {@link Issuer }
   */
  public Issuer getIssuer() {
    return issuer;
  }

  /**
   * Sets the value of the issuer property.
   *
   * @param value allowed object is {@link Issuer }
   */
  public void setIssuer(Issuer value) {
    this.issuer = value;
  }

  /**
   * Gets the value of the suffixNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getSuffixNumber() {
    return suffixNumber;
  }

  /**
   * Sets the value of the suffixNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSuffixNumber(String value) {
    this.suffixNumber = value;
  }

  /**
   * Gets the value of the issuerCountryCode property.
   *
   * @return possible object is {@link String }
   */
  public String getIssuerCountryCode() {
    return issuerCountryCode;
  }

  /**
   * Sets the value of the issuerCountryCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setIssuerCountryCode(String value) {
    this.issuerCountryCode = value;
  }
}
