//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Product complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Product">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Offering">
 *       &lt;sequence>
 *         &lt;element name="weight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Weight" minOccurs="0"/>
 *         &lt;element name="sellingQuantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Product",
    propOrder = {"weight", "sellingQuantity"})
public class Product extends Offering {

  protected Weight weight;
  protected Quantity sellingQuantity;

  /**
   * Gets the value of the weight property.
   *
   * @return possible object is {@link Weight }
   */
  public Weight getWeight() {
    return weight;
  }

  /**
   * Sets the value of the weight property.
   *
   * @param value allowed object is {@link Weight }
   */
  public void setWeight(Weight value) {
    this.weight = value;
  }

  /**
   * Gets the value of the sellingQuantity property.
   *
   * @return possible object is {@link Quantity }
   */
  public Quantity getSellingQuantity() {
    return sellingQuantity;
  }

  /**
   * Sets the value of the sellingQuantity property.
   *
   * @param value allowed object is {@link Quantity }
   */
  public void setSellingQuantity(Quantity value) {
    this.sellingQuantity = value;
  }
}
