//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for SubstitutionLine complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SubstitutionLine">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="O"/>
 *               &lt;enumeration value="S"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="quantity" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Quantity" minOccurs="0"/>
 *         &lt;element name="totalWeight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Weight" minOccurs="0"/>
 *         &lt;element name="isOrderByQuantity" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="totalTaxAmount" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Amount" minOccurs="0"/>
 *         &lt;element name="fulfilledUnitPrice" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Price" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "SubstitutionLine",
    propOrder = {
      "type",
      "quantity",
      "totalWeight",
      "isOrderByQuantity",
      "totalTaxAmount",
      "fulfilledUnitPrice"
    })
@XmlSeeAlso({
  com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation.OrderLine
      .SubstitutionLine.class
})
public class SubstitutionLine {

  protected String type;
  protected Quantity quantity;
  protected Weight totalWeight;
  protected Boolean isOrderByQuantity;
  protected Amount totalTaxAmount;
  protected Price fulfilledUnitPrice;

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the quantity property.
   *
   * @return possible object is {@link Quantity }
   */
  public Quantity getQuantity() {
    return quantity;
  }

  /**
   * Sets the value of the quantity property.
   *
   * @param value allowed object is {@link Quantity }
   */
  public void setQuantity(Quantity value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the totalWeight property.
   *
   * @return possible object is {@link Weight }
   */
  public Weight getTotalWeight() {
    return totalWeight;
  }

  /**
   * Sets the value of the totalWeight property.
   *
   * @param value allowed object is {@link Weight }
   */
  public void setTotalWeight(Weight value) {
    this.totalWeight = value;
  }

  /**
   * Gets the value of the isOrderByQuantity property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsOrderByQuantity() {
    return isOrderByQuantity;
  }

  /**
   * Sets the value of the isOrderByQuantity property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsOrderByQuantity(Boolean value) {
    this.isOrderByQuantity = value;
  }

  /**
   * Gets the value of the totalTaxAmount property.
   *
   * @return possible object is {@link Amount }
   */
  public Amount getTotalTaxAmount() {
    return totalTaxAmount;
  }

  /**
   * Sets the value of the totalTaxAmount property.
   *
   * @param value allowed object is {@link Amount }
   */
  public void setTotalTaxAmount(Amount value) {
    this.totalTaxAmount = value;
  }

  /**
   * Gets the value of the fulfilledUnitPrice property.
   *
   * @return possible object is {@link Price }
   */
  public Price getFulfilledUnitPrice() {
    return fulfilledUnitPrice;
  }

  /**
   * Sets the value of the fulfilledUnitPrice property.
   *
   * @param value allowed object is {@link Price }
   */
  public void setFulfilledUnitPrice(Price value) {
    this.fulfilledUnitPrice = value;
  }
}
