//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.31 at 01:59:04 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.xmlns.walmartstores.com/Header/datatypes/MessageHeader/1.4/}MessageHeader"/>
 *         &lt;element name="MessageBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="customerOrder">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CustomerOrder">
 *                           &lt;sequence>
 *                             &lt;element name="fulfillmentOrder" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentOrder">
 *                                     &lt;sequence>
 *                                       &lt;element name="dispatchMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DispatchMethod" minOccurs="0"/>
 *                                       &lt;element name="fulfillmentMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentMethod" minOccurs="0"/>
 *                                       &lt;element name="orderLines" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}OrderLine">
 *                                               &lt;sequence>
 *                                                 &lt;element name="package" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="packages" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package">
 *                                               &lt;sequence>
 *                                                 &lt;element name="deliveryDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DeliveryDetails" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="salesTransaction" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}SalesTransaction" minOccurs="0"/>
 *                                       &lt;element name="loadGroupNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *                                       &lt;element name="fee" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Fee" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="fulfillmentOrderTotal" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                                       &lt;element name="totalCouponAmount" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Amount" minOccurs="0"/>
 *                                       &lt;element name="loadSequenceNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha10" minOccurs="0"/>
 *                                       &lt;element name="tax" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Tax" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="carrierBag" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CarrierBag" minOccurs="0"/>
 *                                       &lt;element name="totalPromotionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *                                       &lt;element name="promotion" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Promotion" maxOccurs="unbounded" minOccurs="0"/>
 *                                       &lt;element name="richInformation" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}RichInformation" maxOccurs="unbounded" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="paymentCard" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PaymentCard" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element name="paymentAuthorization" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PaymentAuthorization" minOccurs="0"/>
 *                             &lt;element name="originatingNode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Node"/>
 *                             &lt;element name="customerInfo" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="customerDetails" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="customer" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Customer" minOccurs="0"/>
 *                                                 &lt;element name="location" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Location" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="discountCard" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DiscountCard" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="MessageExtensions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}MessageExtension" maxOccurs="5" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"messageHeader", "messageBody"})
@XmlRootElement(name = "UpdateFulfillmentOrderRequest")
public class UpdateFulfillmentOrderRequest {

  @XmlElement(
      name = "MessageHeader",
      namespace = "http://www.xmlns.walmartstores.com/Header/datatypes/MessageHeader/1.4/",
      required = true)
  protected MessageHeader messageHeader;

  @XmlElement(name = "MessageBody", required = true)
  protected UpdateFulfillmentOrderRequest.MessageBody messageBody;

  /**
   * Gets the value of the messageHeader property.
   *
   * @return possible object is {@link MessageHeader }
   */
  public MessageHeader getMessageHeader() {
    return messageHeader;
  }

  /**
   * Sets the value of the messageHeader property.
   *
   * @param value allowed object is {@link MessageHeader }
   */
  public void setMessageHeader(MessageHeader value) {
    this.messageHeader = value;
  }

  /**
   * Gets the value of the messageBody property.
   *
   * @return possible object is {@link UpdateFulfillmentOrderRequest.MessageBody }
   */
  public UpdateFulfillmentOrderRequest.MessageBody getMessageBody() {
    return messageBody;
  }

  /**
   * Sets the value of the messageBody property.
   *
   * @param value allowed object is {@link UpdateFulfillmentOrderRequest.MessageBody }
   */
  public void setMessageBody(UpdateFulfillmentOrderRequest.MessageBody value) {
    this.messageBody = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="customerOrder">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CustomerOrder">
   *                 &lt;sequence>
   *                   &lt;element name="fulfillmentOrder" maxOccurs="unbounded">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentOrder">
   *                           &lt;sequence>
   *                             &lt;element name="dispatchMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DispatchMethod" minOccurs="0"/>
   *                             &lt;element name="fulfillmentMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentMethod" minOccurs="0"/>
   *                             &lt;element name="orderLines" maxOccurs="unbounded" minOccurs="0">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}OrderLine">
   *                                     &lt;sequence>
   *                                       &lt;element name="package" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package" minOccurs="0"/>
   *                                     &lt;/sequence>
   *                                   &lt;/extension>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                             &lt;element name="packages" maxOccurs="unbounded" minOccurs="0">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package">
   *                                     &lt;sequence>
   *                                       &lt;element name="deliveryDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DeliveryDetails" minOccurs="0"/>
   *                                     &lt;/sequence>
   *                                   &lt;/extension>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                             &lt;element name="salesTransaction" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}SalesTransaction" minOccurs="0"/>
   *                             &lt;element name="loadGroupNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
   *                             &lt;element name="fee" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Fee" maxOccurs="unbounded" minOccurs="0"/>
   *                             &lt;element name="fulfillmentOrderTotal" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
   *                             &lt;element name="totalCouponAmount" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Amount" minOccurs="0"/>
   *                             &lt;element name="loadSequenceNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha10" minOccurs="0"/>
   *                             &lt;element name="tax" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Tax" maxOccurs="unbounded" minOccurs="0"/>
   *                             &lt;element name="carrierBag" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CarrierBag" minOccurs="0"/>
   *                             &lt;element name="totalPromotionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
   *                             &lt;element name="promotion" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Promotion" maxOccurs="unbounded" minOccurs="0"/>
   *                             &lt;element name="richInformation" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}RichInformation" maxOccurs="unbounded" minOccurs="0"/>
   *                           &lt;/sequence>
   *                         &lt;/extension>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                   &lt;element name="paymentCard" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PaymentCard" maxOccurs="unbounded" minOccurs="0"/>
   *                   &lt;element name="paymentAuthorization" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PaymentAuthorization" minOccurs="0"/>
   *                   &lt;element name="originatingNode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Node"/>
   *                   &lt;element name="customerInfo" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="customerDetails" minOccurs="0">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                       &lt;element name="customer" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Customer" minOccurs="0"/>
   *                                       &lt;element name="location" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Location" minOccurs="0"/>
   *                                     &lt;/sequence>
   *                                   &lt;/restriction>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                             &lt;element name="discountCard" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DiscountCard" minOccurs="0"/>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/extension>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="MessageExtensions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}MessageExtension" maxOccurs="5" minOccurs="0"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"customerOrder", "messageExtensions"})
  public static class MessageBody {

    @XmlElement(required = true)
    protected UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder customerOrder;

    @XmlElement(name = "MessageExtensions")
    protected List<MessageExtension> messageExtensions;

    /**
     * Gets the value of the customerOrder property.
     *
     * @return possible object is {@link UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder }
     */
    public UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder getCustomerOrder() {
      return customerOrder;
    }

    /**
     * Sets the value of the customerOrder property.
     *
     * @param value allowed object is {@link UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder
     *     }
     */
    public void setCustomerOrder(UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder value) {
      this.customerOrder = value;
    }

    /**
     * Gets the value of the messageExtensions property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the messageExtensions property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getMessageExtensions().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link MessageExtension }
     */
    public List<MessageExtension> getMessageExtensions() {
      if (messageExtensions == null) {
        messageExtensions = new ArrayList<>();
      }
      return this.messageExtensions;
    }

    public void setMessageExtensions(List<MessageExtension> value) {
      this.messageExtensions = null;
      List<MessageExtension> draftl = this.getMessageExtensions();
      draftl.addAll(value);
    }

    /**
     * Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CustomerOrder">
     *       &lt;sequence>
     *         &lt;element name="fulfillmentOrder" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentOrder">
     *                 &lt;sequence>
     *                   &lt;element name="dispatchMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DispatchMethod" minOccurs="0"/>
     *                   &lt;element name="fulfillmentMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentMethod" minOccurs="0"/>
     *                   &lt;element name="orderLines" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}OrderLine">
     *                           &lt;sequence>
     *                             &lt;element name="package" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="packages" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package">
     *                           &lt;sequence>
     *                             &lt;element name="deliveryDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DeliveryDetails" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="salesTransaction" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}SalesTransaction" minOccurs="0"/>
     *                   &lt;element name="loadGroupNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
     *                   &lt;element name="fee" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Fee" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="fulfillmentOrderTotal" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *                   &lt;element name="totalCouponAmount" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Amount" minOccurs="0"/>
     *                   &lt;element name="loadSequenceNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha10" minOccurs="0"/>
     *                   &lt;element name="tax" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Tax" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="carrierBag" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CarrierBag" minOccurs="0"/>
     *                   &lt;element name="totalPromotionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
     *                   &lt;element name="promotion" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Promotion" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element name="richInformation" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}RichInformation" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="paymentCard" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PaymentCard" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="paymentAuthorization" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}PaymentAuthorization" minOccurs="0"/>
     *         &lt;element name="originatingNode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Node"/>
     *         &lt;element name="customerInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="customerDetails" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="customer" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Customer" minOccurs="0"/>
     *                             &lt;element name="location" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Location" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="discountCard" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DiscountCard" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(
        name = "",
        propOrder = {
          "fulfillmentOrder",
          "paymentCard",
          "paymentAuthorization",
          "originatingNode",
          "customerInfo"
        })
    public static class CustomerOrder
        extends com.walmart.fms.infrastructure.integration.gateway.store.dto.forceordercancellation
            .CustomerOrder {

      @XmlElement(required = true)
      protected List<UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder>
          fulfillmentOrder;

      protected List<PaymentCard> paymentCard;
      protected PaymentAuthorization paymentAuthorization;

      @XmlElement(required = true)
      protected Node originatingNode;

      protected UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo customerInfo;

      /**
       * Gets the value of the fulfillmentOrder property.
       *
       * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
       * modification you make to the returned list will be present inside the JAXB object. This is
       * why there is not a <CODE>set</CODE> method for the fulfillmentOrder property.
       *
       * <p>For example, to add a new item, do as follows:
       *
       * <pre>
       *    getFulfillmentOrder().add(newItem);
       * </pre>
       *
       * <p>Objects of the following type(s) are allowed in the list {@link
       * UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder }
       */
      public List<UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder>
          getFulfillmentOrder() {
        if (fulfillmentOrder == null) {
          fulfillmentOrder = new ArrayList<>();
        }
        return this.fulfillmentOrder;
      }

      /**
       * Gets the value of the paymentCard property.
       *
       * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
       * modification you make to the returned list will be present inside the JAXB object. This is
       * why there is not a <CODE>set</CODE> method for the paymentCard property.
       *
       * <p>For example, to add a new item, do as follows:
       *
       * <pre>
       *    getPaymentCard().add(newItem);
       * </pre>
       *
       * <p>Objects of the following type(s) are allowed in the list {@link PaymentCard }
       */
      public List<PaymentCard> getPaymentCard() {
        if (paymentCard == null) {
          paymentCard = new ArrayList<>();
        }
        return this.paymentCard;
      }

      /**
       * Gets the value of the paymentAuthorization property.
       *
       * @return possible object is {@link PaymentAuthorization }
       */
      public PaymentAuthorization getPaymentAuthorization() {
        return paymentAuthorization;
      }

      /**
       * Sets the value of the paymentAuthorization property.
       *
       * @param value allowed object is {@link PaymentAuthorization }
       */
      public void setPaymentAuthorization(PaymentAuthorization value) {
        this.paymentAuthorization = value;
      }

      /**
       * Gets the value of the originatingNode property.
       *
       * @return possible object is {@link Node }
       */
      public Node getOriginatingNode() {
        return originatingNode;
      }

      /**
       * Sets the value of the originatingNode property.
       *
       * @param value allowed object is {@link Node }
       */
      public void setOriginatingNode(Node value) {
        this.originatingNode = value;
      }

      /**
       * Gets the value of the customerInfo property.
       *
       * @return possible object is {@link
       *     UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo }
       */
      public UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo
          getCustomerInfo() {
        return customerInfo;
      }

      /**
       * Sets the value of the customerInfo property.
       *
       * @param value allowed object is {@link
       *     UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo }
       */
      public void setCustomerInfo(
          UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo value) {
        this.customerInfo = value;
      }

      public void setFulfillmentOrder(
          List<UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder> value) {
        this.fulfillmentOrder = null;
        List<UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder> draftl =
            this.getFulfillmentOrder();
        draftl.addAll(value);
      }

      public void setPaymentCard(List<PaymentCard> value) {
        this.paymentCard = null;
        List<PaymentCard> draftl = this.getPaymentCard();
        draftl.addAll(value);
      }

      /**
       * Java class for anonymous complex type.
       *
       * <p>The following schema fragment specifies the expected content contained within this
       * class.
       *
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="customerDetails" minOccurs="0">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="customer" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Customer" minOccurs="0"/>
       *                   &lt;element name="location" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Location" minOccurs="0"/>
       *                 &lt;/sequence>
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *         &lt;element name="discountCard" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DiscountCard" minOccurs="0"/>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(
          name = "",
          propOrder = {"customerDetails", "discountCard"})
      public static class CustomerInfo {

        protected UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo
                .CustomerDetails
            customerDetails;
        protected DiscountCard discountCard;

        /**
         * Gets the value of the customerDetails property.
         *
         * @return possible object is {@link
         *     UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo.CustomerDetails
         *     }
         */
        public UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo.CustomerDetails
            getCustomerDetails() {
          return customerDetails;
        }

        /**
         * Sets the value of the customerDetails property.
         *
         * @param value allowed object is {@link
         *     UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo.CustomerDetails
         *     }
         */
        public void setCustomerDetails(
            UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.CustomerInfo.CustomerDetails
                value) {
          this.customerDetails = value;
        }

        /**
         * Gets the value of the discountCard property.
         *
         * @return possible object is {@link DiscountCard }
         */
        public DiscountCard getDiscountCard() {
          return discountCard;
        }

        /**
         * Sets the value of the discountCard property.
         *
         * @param value allowed object is {@link DiscountCard }
         */
        public void setDiscountCard(DiscountCard value) {
          this.discountCard = value;
        }

        /**
         * Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this
         * class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="customer" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Customer" minOccurs="0"/>
         *         &lt;element name="location" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Location" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(
            name = "",
            propOrder = {"customer", "location"})
        public static class CustomerDetails {

          protected Customer customer;
          protected Location location;

          /**
           * Gets the value of the customer property.
           *
           * @return possible object is {@link Customer }
           */
          public Customer getCustomer() {
            return customer;
          }

          /**
           * Sets the value of the customer property.
           *
           * @param value allowed object is {@link Customer }
           */
          public void setCustomer(Customer value) {
            this.customer = value;
          }

          /**
           * Gets the value of the location property.
           *
           * @return possible object is {@link Location }
           */
          public Location getLocation() {
            return location;
          }

          /**
           * Sets the value of the location property.
           *
           * @param value allowed object is {@link Location }
           */
          public void setLocation(Location value) {
            this.location = value;
          }
        }
      }

      /**
       * Java class for anonymous complex type.
       *
       * <p>The following schema fragment specifies the expected content contained within this
       * class.
       *
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentOrder">
       *       &lt;sequence>
       *         &lt;element name="dispatchMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DispatchMethod" minOccurs="0"/>
       *         &lt;element name="fulfillmentMethod" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}FulfillmentMethod" minOccurs="0"/>
       *         &lt;element name="orderLines" maxOccurs="unbounded" minOccurs="0">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}OrderLine">
       *                 &lt;sequence>
       *                   &lt;element name="package" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package" minOccurs="0"/>
       *                 &lt;/sequence>
       *               &lt;/extension>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *         &lt;element name="packages" maxOccurs="unbounded" minOccurs="0">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package">
       *                 &lt;sequence>
       *                   &lt;element name="deliveryDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DeliveryDetails" minOccurs="0"/>
       *                 &lt;/sequence>
       *               &lt;/extension>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *         &lt;element name="salesTransaction" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}SalesTransaction" minOccurs="0"/>
       *         &lt;element name="loadGroupNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
       *         &lt;element name="fee" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Fee" maxOccurs="unbounded" minOccurs="0"/>
       *         &lt;element name="fulfillmentOrderTotal" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
       *         &lt;element name="totalCouponAmount" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Amount" minOccurs="0"/>
       *         &lt;element name="loadSequenceNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}alpha10" minOccurs="0"/>
       *         &lt;element name="tax" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Tax" maxOccurs="unbounded" minOccurs="0"/>
       *         &lt;element name="carrierBag" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}CarrierBag" minOccurs="0"/>
       *         &lt;element name="totalPromotionAmount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
       *         &lt;element name="promotion" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Promotion" maxOccurs="unbounded" minOccurs="0"/>
       *         &lt;element name="richInformation" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}RichInformation" maxOccurs="unbounded" minOccurs="0"/>
       *       &lt;/sequence>
       *     &lt;/extension>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(
          name = "",
          propOrder = {
            "dispatchMethod",
            "fulfillmentMethod",
            "orderLines",
            "packages",
            "salesTransaction",
            "loadGroupNumber",
            "fee",
            "fulfillmentOrderTotal",
            "totalCouponAmount",
            "loadSequenceNumber",
            "tax",
            "carrierBag",
            "totalPromotionAmount",
            "promotion",
            "richInformation"
          })
      public static class FulfillmentOrder
          extends com.walmart.fms.infrastructure.integration.gateway.store.dto
              .forceordercancellation.FulfillmentOrder {

        protected DispatchMethod dispatchMethod;
        protected FulfillmentMethod fulfillmentMethod;
        protected List<
                UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.OrderLines>
            orderLines;
        protected List<
                UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.Packages>
            packages;
        protected SalesTransaction salesTransaction;

        @XmlSchemaType(name = "unsignedLong")
        protected BigInteger loadGroupNumber;

        protected List<Fee> fee;
        protected Float fulfillmentOrderTotal;
        protected Amount totalCouponAmount;
        protected String loadSequenceNumber;
        protected List<Tax> tax;
        protected CarrierBag carrierBag;
        protected BigDecimal totalPromotionAmount;
        protected List<Promotion> promotion;
        protected List<RichInformation> richInformation;

        /**
         * Gets the value of the dispatchMethod property.
         *
         * @return possible object is {@link DispatchMethod }
         */
        public DispatchMethod getDispatchMethod() {
          return dispatchMethod;
        }

        /**
         * Sets the value of the dispatchMethod property.
         *
         * @param value allowed object is {@link DispatchMethod }
         */
        public void setDispatchMethod(DispatchMethod value) {
          this.dispatchMethod = value;
        }

        /**
         * Gets the value of the fulfillmentMethod property.
         *
         * @return possible object is {@link FulfillmentMethod }
         */
        public FulfillmentMethod getFulfillmentMethod() {
          return fulfillmentMethod;
        }

        /**
         * Sets the value of the fulfillmentMethod property.
         *
         * @param value allowed object is {@link FulfillmentMethod }
         */
        public void setFulfillmentMethod(FulfillmentMethod value) {
          this.fulfillmentMethod = value;
        }

        /**
         * Gets the value of the orderLines property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the orderLines property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getOrderLines().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link
         * UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.OrderLines }
         */
        public List<
                UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.OrderLines>
            getOrderLines() {
          if (orderLines == null) {
            orderLines = new ArrayList<>();
          }
          return this.orderLines;
        }

        /**
         * Gets the value of the packages property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the packages property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getPackages().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link
         * UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.Packages }
         */
        public List<
                UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.Packages>
            getPackages() {
          if (packages == null) {
            packages = new ArrayList<>();
          }
          return this.packages;
        }

        /**
         * Gets the value of the salesTransaction property.
         *
         * @return possible object is {@link SalesTransaction }
         */
        public SalesTransaction getSalesTransaction() {
          return salesTransaction;
        }

        /**
         * Sets the value of the salesTransaction property.
         *
         * @param value allowed object is {@link SalesTransaction }
         */
        public void setSalesTransaction(SalesTransaction value) {
          this.salesTransaction = value;
        }

        /**
         * Gets the value of the loadGroupNumber property.
         *
         * @return possible object is {@link BigInteger }
         */
        public BigInteger getLoadGroupNumber() {
          return loadGroupNumber;
        }

        /**
         * Sets the value of the loadGroupNumber property.
         *
         * @param value allowed object is {@link BigInteger }
         */
        public void setLoadGroupNumber(BigInteger value) {
          this.loadGroupNumber = value;
        }

        /**
         * Gets the value of the fee property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fee property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getFee().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link Fee }
         */
        public List<Fee> getFee() {
          if (fee == null) {
            fee = new ArrayList<>();
          }
          return this.fee;
        }

        /**
         * Gets the value of the fulfillmentOrderTotal property.
         *
         * @return possible object is {@link Float }
         */
        public Float getFulfillmentOrderTotal() {
          return fulfillmentOrderTotal;
        }

        /**
         * Sets the value of the fulfillmentOrderTotal property.
         *
         * @param value allowed object is {@link Float }
         */
        public void setFulfillmentOrderTotal(Float value) {
          this.fulfillmentOrderTotal = value;
        }

        /**
         * Gets the value of the totalCouponAmount property.
         *
         * @return possible object is {@link Amount }
         */
        public Amount getTotalCouponAmount() {
          return totalCouponAmount;
        }

        /**
         * Sets the value of the totalCouponAmount property.
         *
         * @param value allowed object is {@link Amount }
         */
        public void setTotalCouponAmount(Amount value) {
          this.totalCouponAmount = value;
        }

        /**
         * Gets the value of the loadSequenceNumber property.
         *
         * @return possible object is {@link String }
         */
        public String getLoadSequenceNumber() {
          return loadSequenceNumber;
        }

        /**
         * Sets the value of the loadSequenceNumber property.
         *
         * @param value allowed object is {@link String }
         */
        public void setLoadSequenceNumber(String value) {
          this.loadSequenceNumber = value;
        }

        /**
         * Gets the value of the tax property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the tax property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getTax().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link Tax }
         */
        public List<Tax> getTax() {
          if (tax == null) {
            tax = new ArrayList<>();
          }
          return this.tax;
        }

        /**
         * Gets the value of the carrierBag property.
         *
         * @return possible object is {@link CarrierBag }
         */
        public CarrierBag getCarrierBag() {
          return carrierBag;
        }

        /**
         * Sets the value of the carrierBag property.
         *
         * @param value allowed object is {@link CarrierBag }
         */
        public void setCarrierBag(CarrierBag value) {
          this.carrierBag = value;
        }

        /**
         * Gets the value of the totalPromotionAmount property.
         *
         * @return possible object is {@link BigDecimal }
         */
        public BigDecimal getTotalPromotionAmount() {
          return totalPromotionAmount;
        }

        /**
         * Sets the value of the totalPromotionAmount property.
         *
         * @param value allowed object is {@link BigDecimal }
         */
        public void setTotalPromotionAmount(BigDecimal value) {
          this.totalPromotionAmount = value;
        }

        /**
         * Gets the value of the promotion property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the promotion property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getPromotion().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link Promotion }
         */
        public List<Promotion> getPromotion() {
          if (promotion == null) {
            promotion = new ArrayList<>();
          }
          return this.promotion;
        }

        /**
         * Gets the value of the richInformation property.
         *
         * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore
         * any modification you make to the returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the richInformation property.
         *
         * <p>For example, to add a new item, do as follows:
         *
         * <pre>
         *    getRichInformation().add(newItem);
         * </pre>
         *
         * <p>Objects of the following type(s) are allowed in the list {@link RichInformation }
         */
        public List<RichInformation> getRichInformation() {
          if (richInformation == null) {
            richInformation = new ArrayList<>();
          }
          return this.richInformation;
        }

        public void setOrderLines(
            List<
                    UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder
                        .OrderLines>
                value) {
          this.orderLines = null;
          List<UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.OrderLines>
              draftl = this.getOrderLines();
          draftl.addAll(value);
        }

        public void setPackages(
            List<UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.Packages>
                value) {
          this.packages = null;
          List<UpdateFulfillmentOrderRequest.MessageBody.CustomerOrder.FulfillmentOrder.Packages>
              draftl = this.getPackages();
          draftl.addAll(value);
        }

        public void setFee(List<Fee> value) {
          this.fee = null;
          List<Fee> draftl = this.getFee();
          draftl.addAll(value);
        }

        public void setTax(List<Tax> value) {
          this.tax = null;
          List<Tax> draftl = this.getTax();
          draftl.addAll(value);
        }

        public void setPromotion(List<Promotion> value) {
          this.promotion = null;
          List<Promotion> draftl = this.getPromotion();
          draftl.addAll(value);
        }

        public void setRichInformation(List<RichInformation> value) {
          this.richInformation = null;
          List<RichInformation> draftl = this.getRichInformation();
          draftl.addAll(value);
        }

        /**
         * Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this
         * class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}OrderLine">
         *       &lt;sequence>
         *         &lt;element name="package" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(
            name = "",
            propOrder = {"_package"})
        public static class OrderLines extends OrderLine {

          @XmlElement(name = "package")
          protected Package _package;

          /**
           * Gets the value of the package property.
           *
           * @return possible object is {@link Package }
           */
          public Package getPackage() {
            return _package;
          }

          /**
           * Sets the value of the package property.
           *
           * @param value allowed object is {@link Package }
           */
          public void setPackage(Package value) {
            this._package = value;
          }
        }

        /**
         * Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this
         * class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}Package">
         *       &lt;sequence>
         *         &lt;element name="deliveryDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/UpdateFulfillmentOrder/}DeliveryDetails" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(
            name = "",
            propOrder = {"deliveryDetails"})
        public static class Packages extends Package {

          protected DeliveryDetails deliveryDetails;

          /**
           * Gets the value of the deliveryDetails property.
           *
           * @return possible object is {@link DeliveryDetails }
           */
          public DeliveryDetails getDeliveryDetails() {
            return deliveryDetails;
          }

          /**
           * Sets the value of the deliveryDetails property.
           *
           * @param value allowed object is {@link DeliveryDetails }
           */
          public void setDeliveryDetails(DeliveryDetails value) {
            this.deliveryDetails = value;
          }
        }
      }
    }
  }
}
