USE [OMSCOREDB]
GO
CREATE PROCEDURE [OMSCOREDB].[OMS_ORDER_PROCDR]
			@dayToSubs INT,
			@BatchCount INT = 10000
AS
BEGIN
	SELECT 1
	WHILE (@@ROWCOUNT > 0)
	BEGIN
		DELETE	TOP (@BatchCount)
		  FROM	[OMSCOREDB].[OMS_ORDER]
		 WHERE	CAST([CREATED_DATE] AS DATE) <= DATEADD(DAY, -@dayToSubs, GETDATE())
	END
END
GO

USE [OMSCOREDB]
GO
CREATE PROCEDURE [OMSCOREDB].[FULFILLMENT_ORDER_PROCDR]
			@dayToSubs INT,
			@BatchCount INT = 10000
AS
BEGIN
	SELECT 1
	WHILE (@@ROWCOUNT > 0)
	BEGIN
		DELETE	TOP (@BatchCount)
		  FROM	[OMSCOREDB].[FULFILLMENT_ORDER]
		 WHERE	CAST([CREATED_DATE] AS DATE) <= DATEADD(DAY, -@dayToSubs, GETDATE())
	END
END
GO


USE [OMSCOREDB]
GO
CREATE PROCEDURE [OMSCOREDB].[MARKET_PLACE_ORDER_PROCDR]
			@dayToSubs INT,
			@BatchCount INT = 10000
AS
BEGIN
	SELECT 1
	WHILE (@@ROWCOUNT > 0)
	BEGIN
		DELETE	TOP (@BatchCount)
		  FROM	[OMSCOREDB].[MARKET_PLACE_ORDER]
		 WHERE	CAST([CREATED_DATE] AS DATE) <= DATEADD(DAY, -@dayToSubs, GETDATE())
	END
END
GO


USE [OMSCOREDB]
GO
CREATE PROCEDURE [OMSCOREDB].[EGRESS_EVENTS_PROCDR]
			@dayToSubs INT,
			@BatchCount INT = 10000
AS
BEGIN
	SELECT 1
	WHILE (@@ROWCOUNT > 0)
	BEGIN
		DELETE	TOP (@BatchCount)
		  FROM	[OMSCOREDB].[EGRESS_EVENTS]
		 WHERE	CAST([CREATED_DATE] AS DATE) <= DATEADD(DAY, -@dayToSubs, GETDATE())
	END
END
GO

USE [OMSCOREDB]
GO
CREATE PROCEDURE [OMSCOREDB].[MARKET_PLACE_EVENTS_PROCDR]
			@dayToSubs INT,
			@BatchCount INT = 10000
AS
BEGIN
	SELECT 1
	WHILE (@@ROWCOUNT > 0)
	BEGIN
		DELETE	TOP (@BatchCount)
		  FROM	[OMSCOREDB].[MARKET_PLACE_EVENTS]
		 WHERE	CAST([CREATED_DATE] AS DATE) <= DATEADD(DAY, -@dayToSubs, GETDATE())
	END
END
GO