-- Start Of Index Creation --
CREATE INDEX CREATE_DATE_INDEX ON OMSCOREDB.FULFILLMENT_ORDER (CREATED_DATE)

CREATE INDEX CREATE_DATE_INDEX ON OMSCOREDB.MARKET_PLACE_ORDER (CREATED_DATE)

CREATE INDEX CREATE_DATE_INDEX ON OMSCOREDB.OMS_ORDER (CREATED_DATE)

CREATE INDEX CREATE_DATE_INDEX ON OMSCOREDB.EGRESS_EVENTS (CREATED_DATE)

CREATE INDEX CREATE_DATE_INDEX ON OMSCOREDB.MARKET_PLACE_EVENTS (CREATED_DATE)
-- End Of Index Creation --


-- Start Of Altering FK with ON CASCADE DELETE --
ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_ADDRESS
DROP CONSTRAINT FULFILLMENT_ORDER_ADDRESS_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_ADDRESS ADD CONSTRAINT [FULFILLMENT_ORDER_ADDRESS_FK1]
FOREIGN KEY ([REF_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_CONTACT_INFO
DROP CONSTRAINT FULFILLMENT_ORDER_CONTACT_INFO_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_CONTACT_INFO ADD CONSTRAINT [FULFILLMENT_ORDER_CONTACT_INFO_FK1]
FOREIGN KEY ([ORDER_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_LINE
DROP CONSTRAINT FULFILLMENT_ORDER_LINE_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_LINE ADD CONSTRAINT [FULFILLMENT_ORDER_LINE_FK1]
FOREIGN KEY ([ORDER_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_LINE_UPC
DROP CONSTRAINT FULFILLMENT_ORDER_LINE_UPC_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_LINE_UPC ADD CONSTRAINT [FULFILLMENT_ORDER_LINE_UPC_FK1]
FOREIGN KEY ([REF_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER_LINE ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_PICK_LINE_UPC
DROP CONSTRAINT FULFILLMENT_ORDER_PICK_LINE_UPC_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_PICK_LINE_UPC ADD CONSTRAINT [FULFILLMENT_ORDER_PICK_LINE_UPC_FK1]
FOREIGN KEY ([REF_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER_PICKED_LINE ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_PICKED_LINE
DROP CONSTRAINT FULFILLMENT_ORDER_PICKED_LINE_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_PICKED_LINE ADD CONSTRAINT [FULFILLMENT_ORDER_PICKED_LINE_FK1]
FOREIGN KEY ([ORDERED_ITEM_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER_LINE ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_SCHEDULING_INFO
DROP CONSTRAINT FULFILLMENT_ORDER_SCHEDULING_INFO_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_SCHEDULING_INFO ADD CONSTRAINT [FULFILLMENT_ORDER_SCHEDULING_INFO_FK1]
FOREIGN KEY ([REF_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_TIMESTAMPS
DROP CONSTRAINT FULFILLMENT_ORDER_TIMESTAMPS_FK1

ALTER TABLE OMSCOREDB.FULFILLMENT_ORDER_TIMESTAMPS ADD CONSTRAINT [FULFILLMENT_ORDER_TIMESTAMPS_FK1]
FOREIGN KEY ([REF_RECORD_ID]) REFERENCES OMSCOREDB.FULFILLMENT_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.MARKETPLACE_ITEM
DROP CONSTRAINT MARKETPLACE_ITEM_FK1

ALTER TABLE OMSCOREDB.MARKETPLACE_ITEM ADD CONSTRAINT [MARKETPLACE_ITEM_FK1]
FOREIGN KEY ([ORDER_RECORD_ID]) REFERENCES OMSCOREDB.MARKET_PLACE_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.OMS_CUSTOMER_CONTACT_INFO
DROP CONSTRAINT FK36ieq415todnq9jk5cyfe8b8q

ALTER TABLE OMSCOREDB.OMS_CUSTOMER_CONTACT_INFO ADD CONSTRAINT [FK_OMS_CUSTOMER_CONTACT_INFO_FK1]
FOREIGN KEY ([ORDER_RECORD_ID]) REFERENCES OMSCOREDB.OMS_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.OMS_ORDER_ADDRESS_INFO
DROP CONSTRAINT OMS_ORDER_ADDRESS_INFO_FK1

ALTER TABLE OMSCOREDB.OMS_ORDER_ADDRESS_INFO ADD CONSTRAINT [OMS_ORDER_ADDRESS_INFO_FK1]
FOREIGN KEY ([ORDER_RECORD_ID]) REFERENCES OMSCOREDB.OMS_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.OMS_ORDER_ITEM
DROP CONSTRAINT FKl2nwlw69bvi02aq4pkhi7ywes

ALTER TABLE OMSCOREDB.OMS_ORDER_ITEM ADD CONSTRAINT [FK_OMS_ORDER_ITEM_FK1]
FOREIGN KEY ([ORDER_RECORD_ID]) REFERENCES OMSCOREDB.OMS_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.OMS_ORDER_SCHEDULING_INFO
DROP CONSTRAINT OMS_ORDER_SCHEDULING_INFO_FK1

ALTER TABLE OMSCOREDB.OMS_ORDER_SCHEDULING_INFO ADD CONSTRAINT [OMS_ORDER_SCHEDULING_INFO_FK1]
FOREIGN KEY ([ORDER_RECORD_ID]) REFERENCES OMSCOREDB.OMS_ORDER ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.OMS_PICKED_ITEM
DROP CONSTRAINT FK_OMS_PICK_ITEM_FK1

ALTER TABLE OMSCOREDB.OMS_PICKED_ITEM ADD CONSTRAINT [FK_OMS_PICK_ITEM_FK1]
FOREIGN KEY ([ORDER_ITEM_RECORD_ID]) REFERENCES OMSCOREDB.OMS_ORDER_ITEM ([RECORD_ID])
ON DELETE CASCADE


ALTER TABLE OMSCOREDB.OMS_PICKED_ITEM_UPC
DROP CONSTRAINT FKjoxuf3pju0jxm7yp22ou6utfr

ALTER TABLE OMSCOREDB.OMS_PICKED_ITEM_UPC ADD CONSTRAINT [FK_OMS_PICKED_ITEM_UPC_FK1]
FOREIGN KEY ([PICKED_ITEM_RECORD_ID]) REFERENCES OMSCOREDB.OMS_PICKED_ITEM ([RECORD_ID])
ON DELETE CASCADE

-- End Of Altering FK with ON CASCADE DELETE --