//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Account complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Account">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha25" minOccurs="0"/>
 *         &lt;element name="credentials" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Credentials" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Status" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha25" minOccurs="0"/>
 *         &lt;element name="availableAuthenticationRetries" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="voiceAuthorizedApprover" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Name" minOccurs="0"/>
 *         &lt;element name="balance" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Amount" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Account",
    propOrder = {
      "id",
      "credentials",
      "status",
      "type",
      "availableAuthenticationRetries",
      "voiceAuthorizedApprover",
      "balance"
    })
@XmlSeeAlso({CustomerAccount.class})
public class Account {

  protected String id;
  protected Credentials credentials;
  protected Status status;
  protected String type;

  @XmlSchemaType(name = "unsignedShort")
  protected Integer availableAuthenticationRetries;

  protected Name voiceAuthorizedApprover;
  protected Amount balance;

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setId(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the credentials property.
   *
   * @return possible object is {@link Credentials }
   */
  public Credentials getCredentials() {
    return credentials;
  }

  /**
   * Sets the value of the credentials property.
   *
   * @param value allowed object is {@link Credentials }
   */
  public void setCredentials(Credentials value) {
    this.credentials = value;
  }

  /**
   * Gets the value of the status property.
   *
   * @return possible object is {@link Status }
   */
  public Status getStatus() {
    return status;
  }

  /**
   * Sets the value of the status property.
   *
   * @param value allowed object is {@link Status }
   */
  public void setStatus(Status value) {
    this.status = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the availableAuthenticationRetries property.
   *
   * @return possible object is {@link Integer }
   */
  public Integer getAvailableAuthenticationRetries() {
    return availableAuthenticationRetries;
  }

  /**
   * Sets the value of the availableAuthenticationRetries property.
   *
   * @param value allowed object is {@link Integer }
   */
  public void setAvailableAuthenticationRetries(Integer value) {
    this.availableAuthenticationRetries = value;
  }

  /**
   * Gets the value of the voiceAuthorizedApprover property.
   *
   * @return possible object is {@link Name }
   */
  public Name getVoiceAuthorizedApprover() {
    return voiceAuthorizedApprover;
  }

  /**
   * Sets the value of the voiceAuthorizedApprover property.
   *
   * @param value allowed object is {@link Name }
   */
  public void setVoiceAuthorizedApprover(Name value) {
    this.voiceAuthorizedApprover = value;
  }

  /**
   * Gets the value of the balance property.
   *
   * @return possible object is {@link Amount }
   */
  public Amount getBalance() {
    return balance;
  }

  /**
   * Sets the value of the balance property.
   *
   * @param value allowed object is {@link Amount }
   */
  public void setBalance(Amount value) {
    this.balance = value;
  }
}
