//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Address complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Address">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="addressLine1" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha100" minOccurs="0"/>
 *         &lt;element name="addressLine2" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha100" minOccurs="0"/>
 *         &lt;element name="addressLine3" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha100" minOccurs="0"/>
 *         &lt;element name="addressLine4" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha100" minOccurs="0"/>
 *         &lt;element name="city" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha80" minOccurs="0"/>
 *         &lt;element name="county" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha80" minOccurs="0"/>
 *         &lt;element name="state" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha3" minOccurs="0"/>
 *         &lt;element name="zip" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha20" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}AddressType" minOccurs="0"/>
 *         &lt;element name="country" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Country" minOccurs="0"/>
 *         &lt;element name="memo" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Address",
    propOrder = {
      "addressLine1",
      "addressLine2",
      "addressLine3",
      "addressLine4",
      "city",
      "county",
      "state",
      "zip",
      "type",
      "country",
      "memo"
    })
public class Address {

  protected String addressLine1;
  protected String addressLine2;
  protected String addressLine3;
  protected String addressLine4;
  protected String city;
  protected String county;
  protected String state;
  protected String zip;
  protected AddressType type;
  protected Country country;
  protected String memo;

  /**
   * Gets the value of the addressLine1 property.
   *
   * @return possible object is {@link String }
   */
  public String getAddressLine1() {
    return addressLine1;
  }

  /**
   * Sets the value of the addressLine1 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAddressLine1(String value) {
    this.addressLine1 = value;
  }

  /**
   * Gets the value of the addressLine2 property.
   *
   * @return possible object is {@link String }
   */
  public String getAddressLine2() {
    return addressLine2;
  }

  /**
   * Sets the value of the addressLine2 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAddressLine2(String value) {
    this.addressLine2 = value;
  }

  /**
   * Gets the value of the addressLine3 property.
   *
   * @return possible object is {@link String }
   */
  public String getAddressLine3() {
    return addressLine3;
  }

  /**
   * Sets the value of the addressLine3 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAddressLine3(String value) {
    this.addressLine3 = value;
  }

  /**
   * Gets the value of the addressLine4 property.
   *
   * @return possible object is {@link String }
   */
  public String getAddressLine4() {
    return addressLine4;
  }

  /**
   * Sets the value of the addressLine4 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAddressLine4(String value) {
    this.addressLine4 = value;
  }

  /**
   * Gets the value of the city property.
   *
   * @return possible object is {@link String }
   */
  public String getCity() {
    return city;
  }

  /**
   * Sets the value of the city property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCity(String value) {
    this.city = value;
  }

  /**
   * Gets the value of the county property.
   *
   * @return possible object is {@link String }
   */
  public String getCounty() {
    return county;
  }

  /**
   * Sets the value of the county property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCounty(String value) {
    this.county = value;
  }

  /**
   * Gets the value of the state property.
   *
   * @return possible object is {@link String }
   */
  public String getState() {
    return state;
  }

  /**
   * Sets the value of the state property.
   *
   * @param value allowed object is {@link String }
   */
  public void setState(String value) {
    this.state = value;
  }

  /**
   * Gets the value of the zip property.
   *
   * @return possible object is {@link String }
   */
  public String getZip() {
    return zip;
  }

  /**
   * Sets the value of the zip property.
   *
   * @param value allowed object is {@link String }
   */
  public void setZip(String value) {
    this.zip = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link AddressType }
   */
  public AddressType getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link AddressType }
   */
  public void setType(AddressType value) {
    this.type = value;
  }

  /**
   * Gets the value of the country property.
   *
   * @return possible object is {@link Country }
   */
  public Country getCountry() {
    return country;
  }

  /**
   * Sets the value of the country property.
   *
   * @param value allowed object is {@link Country }
   */
  public void setCountry(Country value) {
    this.country = value;
  }

  /**
   * Gets the value of the memo property.
   *
   * @return possible object is {@link String }
   */
  public String getMemo() {
    return memo;
  }

  /**
   * Sets the value of the memo property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMemo(String value) {
    this.memo = value;
  }
}
