//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Dimensions complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Dimensions">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="depth" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="uom" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha20" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Dimensions",
    propOrder = {"height", "width", "depth", "uom"})
public class Dimensions {

  protected BigDecimal height;
  protected BigDecimal width;
  protected BigDecimal depth;
  protected String uom;

  /**
   * Gets the value of the height property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getHeight() {
    return height;
  }

  /**
   * Sets the value of the height property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setHeight(BigDecimal value) {
    this.height = value;
  }

  /**
   * Gets the value of the width property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getWidth() {
    return width;
  }

  /**
   * Sets the value of the width property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setWidth(BigDecimal value) {
    this.width = value;
  }

  /**
   * Gets the value of the depth property.
   *
   * @return possible object is {@link BigDecimal }
   */
  public BigDecimal getDepth() {
    return depth;
  }

  /**
   * Sets the value of the depth property.
   *
   * @param value allowed object is {@link BigDecimal }
   */
  public void setDepth(BigDecimal value) {
    this.depth = value;
  }

  /**
   * Gets the value of the uom property.
   *
   * @return possible object is {@link String }
   */
  public String getUom() {
    return uom;
  }

  /**
   * Sets the value of the uom property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUom(String value) {
    this.uom = value;
  }
}
