//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Java class for FulfillmentOrder complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FulfillmentOrder">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="orderHeader" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}OrderHeader" minOccurs="0"/>
 *         &lt;element name="orderType" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha20" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Status" minOccurs="0"/>
 *         &lt;element name="node" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Node"/>
 *         &lt;element name="pickupDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}PickupDetails" minOccurs="0"/>
 *         &lt;element name="deliveryDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}DeliveryDetails" minOccurs="0"/>
 *         &lt;element name="returnDetails" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}ReturnDetails" minOccurs="0"/>
 *         &lt;element name="totalCouponAmount" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="fee" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Fee" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="plannedDateForFulfillment" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="pickingInstructions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}PickingInstructions" minOccurs="0"/>
 *         &lt;element name="loadGroupNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="loadSequenceNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha10" minOccurs="0"/>
 *         &lt;element name="togetherCode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha2" minOccurs="0"/>
 *         &lt;element name="fulfillmentOrderTotal" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *         &lt;element name="isShipTogether" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isPrepaid" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="dispenseInstructionText" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha512" minOccurs="0"/>
 *         &lt;element name="dispenseMessageText" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha512" minOccurs="0"/>
 *         &lt;element name="returnDC" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Node" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "FulfillmentOrder",
    propOrder = {
      "requestNumber",
      "orderHeader",
      "orderType",
      "status",
      "node",
      "pickupDetails",
      "deliveryDetails",
      "returnDetails",
      "totalCouponAmount",
      "fee",
      "plannedDateForFulfillment",
      "pickingInstructions",
      "loadGroupNumber",
      "loadSequenceNumber",
      "togetherCode",
      "fulfillmentOrderTotal",
      "isShipTogether",
      "isPrepaid",
      "dueDate",
      "dispenseInstructionText",
      "dispenseMessageText",
      "returnDC"
    })
@XmlSeeAlso({
  com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload
      .PlaceFulfillmentOrderRequest.MessageBody.CustomerOrderInfo.CustomerOrder.FulfillmentOrders
      .class
})
public class FulfillmentOrder {

  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger requestNumber;

  protected OrderHeader orderHeader;
  protected String orderType;
  protected Status status;

  @XmlElement(required = true)
  protected Node node;

  protected PickupDetails pickupDetails;
  protected DeliveryDetails deliveryDetails;
  protected ReturnDetails returnDetails;
  protected Float totalCouponAmount;
  protected List<Fee> fee;

  @XmlSchemaType(name = "date")
  protected XMLGregorianCalendar plannedDateForFulfillment;

  protected PickingInstructions pickingInstructions;

  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger loadGroupNumber;

  protected String loadSequenceNumber;
  protected String togetherCode;
  protected Float fulfillmentOrderTotal;
  protected Boolean isShipTogether;
  protected Boolean isPrepaid;

  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar dueDate;

  protected String dispenseInstructionText;
  protected String dispenseMessageText;
  protected Node returnDC;

  /**
   * Gets the value of the requestNumber property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getRequestNumber() {
    return requestNumber;
  }

  /**
   * Sets the value of the requestNumber property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setRequestNumber(BigInteger value) {
    this.requestNumber = value;
  }

  /**
   * Gets the value of the orderHeader property.
   *
   * @return possible object is {@link OrderHeader }
   */
  public OrderHeader getOrderHeader() {
    return orderHeader;
  }

  /**
   * Sets the value of the orderHeader property.
   *
   * @param value allowed object is {@link OrderHeader }
   */
  public void setOrderHeader(OrderHeader value) {
    this.orderHeader = value;
  }

  /**
   * Gets the value of the orderType property.
   *
   * @return possible object is {@link String }
   */
  public String getOrderType() {
    return orderType;
  }

  /**
   * Sets the value of the orderType property.
   *
   * @param value allowed object is {@link String }
   */
  public void setOrderType(String value) {
    this.orderType = value;
  }

  /**
   * Gets the value of the status property.
   *
   * @return possible object is {@link Status }
   */
  public Status getStatus() {
    return status;
  }

  /**
   * Sets the value of the status property.
   *
   * @param value allowed object is {@link Status }
   */
  public void setStatus(Status value) {
    this.status = value;
  }

  /**
   * Gets the value of the node property.
   *
   * @return possible object is {@link Node }
   */
  public Node getNode() {
    return node;
  }

  /**
   * Sets the value of the node property.
   *
   * @param value allowed object is {@link Node }
   */
  public void setNode(Node value) {
    this.node = value;
  }

  /**
   * Gets the value of the pickupDetails property.
   *
   * @return possible object is {@link PickupDetails }
   */
  public PickupDetails getPickupDetails() {
    return pickupDetails;
  }

  /**
   * Sets the value of the pickupDetails property.
   *
   * @param value allowed object is {@link PickupDetails }
   */
  public void setPickupDetails(PickupDetails value) {
    this.pickupDetails = value;
  }

  /**
   * Gets the value of the deliveryDetails property.
   *
   * @return possible object is {@link DeliveryDetails }
   */
  public DeliveryDetails getDeliveryDetails() {
    return deliveryDetails;
  }

  /**
   * Sets the value of the deliveryDetails property.
   *
   * @param value allowed object is {@link DeliveryDetails }
   */
  public void setDeliveryDetails(DeliveryDetails value) {
    this.deliveryDetails = value;
  }

  /**
   * Gets the value of the returnDetails property.
   *
   * @return possible object is {@link ReturnDetails }
   */
  public ReturnDetails getReturnDetails() {
    return returnDetails;
  }

  /**
   * Sets the value of the returnDetails property.
   *
   * @param value allowed object is {@link ReturnDetails }
   */
  public void setReturnDetails(ReturnDetails value) {
    this.returnDetails = value;
  }

  /**
   * Gets the value of the totalCouponAmount property.
   *
   * @return possible object is {@link Float }
   */
  public Float getTotalCouponAmount() {
    return totalCouponAmount;
  }

  /**
   * Sets the value of the totalCouponAmount property.
   *
   * @param value allowed object is {@link Float }
   */
  public void setTotalCouponAmount(Float value) {
    this.totalCouponAmount = value;
  }

  /**
   * Gets the value of the fee property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the fee property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getFee().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link Fee }
   */
  public List<Fee> getFee() {
    if (fee == null) {
      fee = new ArrayList<>();
    }
    return this.fee;
  }

  /**
   * Gets the value of the plannedDateForFulfillment property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getPlannedDateForFulfillment() {
    return plannedDateForFulfillment;
  }

  /**
   * Sets the value of the plannedDateForFulfillment property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setPlannedDateForFulfillment(XMLGregorianCalendar value) {
    this.plannedDateForFulfillment = value;
  }

  /**
   * Gets the value of the pickingInstructions property.
   *
   * @return possible object is {@link PickingInstructions }
   */
  public PickingInstructions getPickingInstructions() {
    return pickingInstructions;
  }

  /**
   * Sets the value of the pickingInstructions property.
   *
   * @param value allowed object is {@link PickingInstructions }
   */
  public void setPickingInstructions(PickingInstructions value) {
    this.pickingInstructions = value;
  }

  /**
   * Gets the value of the loadGroupNumber property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getLoadGroupNumber() {
    return loadGroupNumber;
  }

  /**
   * Sets the value of the loadGroupNumber property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setLoadGroupNumber(BigInteger value) {
    this.loadGroupNumber = value;
  }

  /**
   * Gets the value of the loadSequenceNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getLoadSequenceNumber() {
    return loadSequenceNumber;
  }

  /**
   * Sets the value of the loadSequenceNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLoadSequenceNumber(String value) {
    this.loadSequenceNumber = value;
  }

  /**
   * Gets the value of the togetherCode property.
   *
   * @return possible object is {@link String }
   */
  public String getTogetherCode() {
    return togetherCode;
  }

  /**
   * Sets the value of the togetherCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTogetherCode(String value) {
    this.togetherCode = value;
  }

  /**
   * Gets the value of the fulfillmentOrderTotal property.
   *
   * @return possible object is {@link Float }
   */
  public Float getFulfillmentOrderTotal() {
    return fulfillmentOrderTotal;
  }

  /**
   * Sets the value of the fulfillmentOrderTotal property.
   *
   * @param value allowed object is {@link Float }
   */
  public void setFulfillmentOrderTotal(Float value) {
    this.fulfillmentOrderTotal = value;
  }

  /**
   * Gets the value of the isShipTogether property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsShipTogether() {
    return isShipTogether;
  }

  /**
   * Sets the value of the isShipTogether property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsShipTogether(Boolean value) {
    this.isShipTogether = value;
  }

  /**
   * Gets the value of the isPrepaid property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsPrepaid() {
    return isPrepaid;
  }

  /**
   * Sets the value of the isPrepaid property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsPrepaid(Boolean value) {
    this.isPrepaid = value;
  }

  /**
   * Gets the value of the dueDate property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getDueDate() {
    return dueDate;
  }

  /**
   * Sets the value of the dueDate property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setDueDate(XMLGregorianCalendar value) {
    this.dueDate = value;
  }

  /**
   * Gets the value of the dispenseInstructionText property.
   *
   * @return possible object is {@link String }
   */
  public String getDispenseInstructionText() {
    return dispenseInstructionText;
  }

  /**
   * Sets the value of the dispenseInstructionText property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDispenseInstructionText(String value) {
    this.dispenseInstructionText = value;
  }

  /**
   * Gets the value of the dispenseMessageText property.
   *
   * @return possible object is {@link String }
   */
  public String getDispenseMessageText() {
    return dispenseMessageText;
  }

  /**
   * Sets the value of the dispenseMessageText property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDispenseMessageText(String value) {
    this.dispenseMessageText = value;
  }

  /**
   * Gets the value of the returnDC property.
   *
   * @return possible object is {@link Node }
   */
  public Node getReturnDC() {
    return returnDC;
  }

  /**
   * Sets the value of the returnDC property.
   *
   * @param value allowed object is {@link Node }
   */
  public void setReturnDC(Node value) {
    this.returnDC = value;
  }

  public void setFee(List<Fee> value) {
    this.fee = null;
    List<Fee> draftl = this.getFee();
    draftl.addAll(value);
  }
}
