//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Location complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Location">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="locationAddress" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Address" minOccurs="0"/>
 *         &lt;element name="countryCode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha2"/>
 *         &lt;element name="country" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="globalLocationNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha100" minOccurs="0"/>
 *         &lt;element name="currency" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Currency" minOccurs="0"/>
 *         &lt;element name="geoCode" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Language" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Location",
    propOrder = {
      "locationAddress",
      "countryCode",
      "country",
      "globalLocationNumber",
      "name",
      "currency",
      "geoCode",
      "language"
    })
public class Location {

  protected Address locationAddress;

  @XmlElement(required = true)
  protected String countryCode;

  protected String country;

  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger globalLocationNumber;

  protected String name;
  protected Currency currency;

  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger geoCode;

  protected Language language;

  /**
   * Gets the value of the locationAddress property.
   *
   * @return possible object is {@link Address }
   */
  public Address getLocationAddress() {
    return locationAddress;
  }

  /**
   * Sets the value of the locationAddress property.
   *
   * @param value allowed object is {@link Address }
   */
  public void setLocationAddress(Address value) {
    this.locationAddress = value;
  }

  /**
   * Gets the value of the countryCode property.
   *
   * @return possible object is {@link String }
   */
  public String getCountryCode() {
    return countryCode;
  }

  /**
   * Sets the value of the countryCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCountryCode(String value) {
    this.countryCode = value;
  }

  /**
   * Gets the value of the country property.
   *
   * @return possible object is {@link String }
   */
  public String getCountry() {
    return country;
  }

  /**
   * Sets the value of the country property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCountry(String value) {
    this.country = value;
  }

  /**
   * Gets the value of the globalLocationNumber property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getGlobalLocationNumber() {
    return globalLocationNumber;
  }

  /**
   * Sets the value of the globalLocationNumber property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setGlobalLocationNumber(BigInteger value) {
    this.globalLocationNumber = value;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the currency property.
   *
   * @return possible object is {@link Currency }
   */
  public Currency getCurrency() {
    return currency;
  }

  /**
   * Sets the value of the currency property.
   *
   * @param value allowed object is {@link Currency }
   */
  public void setCurrency(Currency value) {
    this.currency = value;
  }

  /**
   * Gets the value of the geoCode property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getGeoCode() {
    return geoCode;
  }

  /**
   * Sets the value of the geoCode property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setGeoCode(BigInteger value) {
    this.geoCode = value;
  }

  /**
   * Gets the value of the language property.
   *
   * @return possible object is {@link Language }
   */
  public Language getLanguage() {
    return language;
  }

  /**
   * Sets the value of the language property.
   *
   * @param value allowed object is {@link Language }
   */
  public void setLanguage(Language value) {
    this.language = value;
  }
}
