//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for MembershipAccount complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MembershipAccount">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}CustomerAccount">
 *       &lt;sequence>
 *         &lt;element name="membershipNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="membershipType" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}MembershipAccountType" minOccurs="0"/>
 *         &lt;element name="company" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Company" minOccurs="0"/>
 *         &lt;element name="createdForLocation" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Location" minOccurs="0"/>
 *         &lt;element name="cardholderPrefixNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha10"/>
 *         &lt;element name="cardHolderNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha10"/>
 *         &lt;element name="languageCode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "MembershipAccount",
    propOrder = {
      "membershipNumber",
      "membershipType",
      "company",
      "createdForLocation",
      "cardholderPrefixNumber",
      "cardHolderNumber",
      "languageCode"
    })
public class MembershipAccount extends CustomerAccount {

  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger membershipNumber;

  protected MembershipAccountType membershipType;
  protected Company company;
  protected Location createdForLocation;

  @XmlElement(required = true)
  protected String cardholderPrefixNumber;

  @XmlElement(required = true)
  protected String cardHolderNumber;

  protected String languageCode;

  /**
   * Gets the value of the membershipNumber property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getMembershipNumber() {
    return membershipNumber;
  }

  /**
   * Sets the value of the membershipNumber property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setMembershipNumber(BigInteger value) {
    this.membershipNumber = value;
  }

  /**
   * Gets the value of the membershipType property.
   *
   * @return possible object is {@link MembershipAccountType }
   */
  public MembershipAccountType getMembershipType() {
    return membershipType;
  }

  /**
   * Sets the value of the membershipType property.
   *
   * @param value allowed object is {@link MembershipAccountType }
   */
  public void setMembershipType(MembershipAccountType value) {
    this.membershipType = value;
  }

  /**
   * Gets the value of the company property.
   *
   * @return possible object is {@link Company }
   */
  public Company getCompany() {
    return company;
  }

  /**
   * Sets the value of the company property.
   *
   * @param value allowed object is {@link Company }
   */
  public void setCompany(Company value) {
    this.company = value;
  }

  /**
   * Gets the value of the createdForLocation property.
   *
   * @return possible object is {@link Location }
   */
  public Location getCreatedForLocation() {
    return createdForLocation;
  }

  /**
   * Sets the value of the createdForLocation property.
   *
   * @param value allowed object is {@link Location }
   */
  public void setCreatedForLocation(Location value) {
    this.createdForLocation = value;
  }

  /**
   * Gets the value of the cardholderPrefixNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getCardholderPrefixNumber() {
    return cardholderPrefixNumber;
  }

  /**
   * Sets the value of the cardholderPrefixNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCardholderPrefixNumber(String value) {
    this.cardholderPrefixNumber = value;
  }

  /**
   * Gets the value of the cardHolderNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getCardHolderNumber() {
    return cardHolderNumber;
  }

  /**
   * Sets the value of the cardHolderNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCardHolderNumber(String value) {
    this.cardHolderNumber = value;
  }

  /**
   * Gets the value of the languageCode property.
   *
   * @return possible object is {@link String }
   */
  public String getLanguageCode() {
    return languageCode;
  }

  /**
   * Sets the value of the languageCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLanguageCode(String value) {
    this.languageCode = value;
  }
}
