//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for MessageHeader complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MessageHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SubId" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255"/>
 *         &lt;element name="CnsmrId" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255"/>
 *         &lt;element name="SrvcNm" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255"/>
 *         &lt;element name="AppId" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="TranId" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="UsrNm" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="Pwd" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="SrcSysId" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="Version" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255"/>
 *         &lt;element name="ConfCd" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255">
 *               &lt;enumeration value="Always"/>
 *               &lt;enumeration value="ConfirmOnArrival"/>
 *               &lt;enumeration value="ConfirmOnDelivery"/>
 *               &lt;enumeration value="None"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "MessageHeader",
    namespace = "http://www.xmlns.walmartstores.com/Header/datatypes/MessageHeader/1.4/",
    propOrder = {
      "subId",
      "cnsmrId",
      "srvcNm",
      "appId",
      "tranId",
      "usrNm",
      "pwd",
      "srcSysId",
      "version",
      "confCd"
    })
public class MessageHeader {

  @XmlElement(name = "SubId", required = true)
  protected String subId;

  @XmlElement(name = "CnsmrId", required = true)
  protected String cnsmrId;

  @XmlElement(name = "SrvcNm", required = true)
  protected String srvcNm;

  @XmlElement(name = "AppId")
  protected String appId;

  @XmlElement(name = "TranId")
  protected String tranId;

  @XmlElement(name = "UsrNm")
  protected String usrNm;

  @XmlElement(name = "Pwd")
  protected String pwd;

  @XmlElement(name = "SrcSysId")
  protected String srcSysId;

  @XmlElement(name = "Version", required = true)
  protected String version;

  @XmlElement(name = "ConfCd")
  protected String confCd;

  /**
   * Gets the value of the subId property.
   *
   * @return possible object is {@link String }
   */
  public String getSubId() {
    return subId;
  }

  /**
   * Sets the value of the subId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSubId(String value) {
    this.subId = value;
  }

  /**
   * Gets the value of the cnsmrId property.
   *
   * @return possible object is {@link String }
   */
  public String getCnsmrId() {
    return cnsmrId;
  }

  /**
   * Sets the value of the cnsmrId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCnsmrId(String value) {
    this.cnsmrId = value;
  }

  /**
   * Gets the value of the srvcNm property.
   *
   * @return possible object is {@link String }
   */
  public String getSrvcNm() {
    return srvcNm;
  }

  /**
   * Sets the value of the srvcNm property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSrvcNm(String value) {
    this.srvcNm = value;
  }

  /**
   * Gets the value of the appId property.
   *
   * @return possible object is {@link String }
   */
  public String getAppId() {
    return appId;
  }

  /**
   * Sets the value of the appId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAppId(String value) {
    this.appId = value;
  }

  /**
   * Gets the value of the tranId property.
   *
   * @return possible object is {@link String }
   */
  public String getTranId() {
    return tranId;
  }

  /**
   * Sets the value of the tranId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTranId(String value) {
    this.tranId = value;
  }

  /**
   * Gets the value of the usrNm property.
   *
   * @return possible object is {@link String }
   */
  public String getUsrNm() {
    return usrNm;
  }

  /**
   * Sets the value of the usrNm property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUsrNm(String value) {
    this.usrNm = value;
  }

  /**
   * Gets the value of the pwd property.
   *
   * @return possible object is {@link String }
   */
  public String getPwd() {
    return pwd;
  }

  /**
   * Sets the value of the pwd property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPwd(String value) {
    this.pwd = value;
  }

  /**
   * Gets the value of the srcSysId property.
   *
   * @return possible object is {@link String }
   */
  public String getSrcSysId() {
    return srcSysId;
  }

  /**
   * Sets the value of the srcSysId property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSrcSysId(String value) {
    this.srcSysId = value;
  }

  /**
   * Gets the value of the version property.
   *
   * @return possible object is {@link String }
   */
  public String getVersion() {
    return version;
  }

  /**
   * Sets the value of the version property.
   *
   * @param value allowed object is {@link String }
   */
  public void setVersion(String value) {
    this.version = value;
  }

  /**
   * Gets the value of the confCd property.
   *
   * @return possible object is {@link String }
   */
  public String getConfCd() {
    return confCd;
  }

  /**
   * Sets the value of the confCd property.
   *
   * @param value allowed object is {@link String }
   */
  public void setConfCd(String value) {
    this.confCd = value;
  }
}
