//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Message complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Message">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageLine1" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha600" minOccurs="0"/>
 *         &lt;element name="messageLine2" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha600" minOccurs="0"/>
 *         &lt;element name="messageLine3" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha600" minOccurs="0"/>
 *         &lt;element name="messageLine4" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha600" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Message",
    propOrder = {"messageLine1", "messageLine2", "messageLine3", "messageLine4"})
public class Message {

  protected String messageLine1;
  protected String messageLine2;
  protected String messageLine3;
  protected String messageLine4;

  /**
   * Gets the value of the messageLine1 property.
   *
   * @return possible object is {@link String }
   */
  public String getMessageLine1() {
    return messageLine1;
  }

  /**
   * Sets the value of the messageLine1 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMessageLine1(String value) {
    this.messageLine1 = value;
  }

  /**
   * Gets the value of the messageLine2 property.
   *
   * @return possible object is {@link String }
   */
  public String getMessageLine2() {
    return messageLine2;
  }

  /**
   * Sets the value of the messageLine2 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMessageLine2(String value) {
    this.messageLine2 = value;
  }

  /**
   * Gets the value of the messageLine3 property.
   *
   * @return possible object is {@link String }
   */
  public String getMessageLine3() {
    return messageLine3;
  }

  /**
   * Sets the value of the messageLine3 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMessageLine3(String value) {
    this.messageLine3 = value;
  }

  /**
   * Gets the value of the messageLine4 property.
   *
   * @return possible object is {@link String }
   */
  public String getMessageLine4() {
    return messageLine4;
  }

  /**
   * Sets the value of the messageLine4 property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMessageLine4(String value) {
    this.messageLine4 = value;
  }
}
