//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Offering complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Offering">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="richInformation" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}RichInformation" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha100" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha512" minOccurs="0"/>
 *         &lt;element name="secondaryDescription" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha512" minOccurs="0"/>
 *         &lt;element name="globalTradeItem" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}GlobalTradeItem" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="price" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Price" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha20" minOccurs="0"/>
 *         &lt;element name="isAssociateDiscountable" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="chargeCodes" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}ChargeCode" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="department" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Department" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Offering",
    propOrder = {
      "id",
      "richInformation",
      "name",
      "description",
      "secondaryDescription",
      "globalTradeItem",
      "price",
      "type",
      "isAssociateDiscountable",
      "chargeCodes",
      "department"
    })
@XmlSeeAlso({Product.class})
public class Offering {

  @XmlSchemaType(name = "unsignedInt")
  protected Long id;

  protected List<RichInformation> richInformation;
  protected String name;
  protected String description;
  protected String secondaryDescription;
  protected List<GlobalTradeItem> globalTradeItem;
  protected Price price;
  protected String type;
  protected Boolean isAssociateDiscountable;
  protected List<ChargeCode> chargeCodes;
  protected Department department;

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link Long }
   */
  public Long getId() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link Long }
   */
  public void setId(Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the richInformation property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the richInformation property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRichInformation().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link RichInformation }
   */
  public List<RichInformation> getRichInformation() {
    if (richInformation == null) {
      richInformation = new ArrayList<>();
    }
    return this.richInformation;
  }

  /**
   * Gets the value of the name property.
   *
   * @return possible object is {@link String }
   */
  public String getName() {
    return name;
  }

  /**
   * Sets the value of the name property.
   *
   * @param value allowed object is {@link String }
   */
  public void setName(String value) {
    this.name = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the secondaryDescription property.
   *
   * @return possible object is {@link String }
   */
  public String getSecondaryDescription() {
    return secondaryDescription;
  }

  /**
   * Sets the value of the secondaryDescription property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSecondaryDescription(String value) {
    this.secondaryDescription = value;
  }

  /**
   * Gets the value of the globalTradeItem property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the globalTradeItem property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getGlobalTradeItem().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link GlobalTradeItem }
   */
  public List<GlobalTradeItem> getGlobalTradeItem() {
    if (globalTradeItem == null) {
      globalTradeItem = new ArrayList<>();
    }
    return this.globalTradeItem;
  }

  /**
   * Gets the value of the price property.
   *
   * @return possible object is {@link Price }
   */
  public Price getPrice() {
    return price;
  }

  /**
   * Sets the value of the price property.
   *
   * @param value allowed object is {@link Price }
   */
  public void setPrice(Price value) {
    this.price = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the isAssociateDiscountable property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsAssociateDiscountable() {
    return isAssociateDiscountable;
  }

  /**
   * Sets the value of the isAssociateDiscountable property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsAssociateDiscountable(Boolean value) {
    this.isAssociateDiscountable = value;
  }

  /**
   * Gets the value of the chargeCodes property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the chargeCodes property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getChargeCodes().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link ChargeCode }
   */
  public List<ChargeCode> getChargeCodes() {
    if (chargeCodes == null) {
      chargeCodes = new ArrayList<>();
    }
    return this.chargeCodes;
  }

  /**
   * Gets the value of the department property.
   *
   * @return possible object is {@link Department }
   */
  public Department getDepartment() {
    return department;
  }

  /**
   * Sets the value of the department property.
   *
   * @param value allowed object is {@link Department }
   */
  public void setDepartment(Department value) {
    this.department = value;
  }

  public void setRichInformation(List<RichInformation> value) {
    this.richInformation = null;
    List<RichInformation> draftl = this.getRichInformation();
    draftl.addAll(value);
  }

  public void setGlobalTradeItem(List<GlobalTradeItem> value) {
    this.globalTradeItem = null;
    List<GlobalTradeItem> draftl = this.getGlobalTradeItem();
    draftl.addAll(value);
  }

  public void setChargeCodes(List<ChargeCode> value) {
    this.chargeCodes = null;
    List<ChargeCode> draftl = this.getChargeCodes();
    draftl.addAll(value);
  }
}
