//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Java class for OrderHeader complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="OrderHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="orderNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="orderPlacedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="numberOfOrderLines" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="expirationDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "OrderHeader",
    propOrder = {"orderNumber", "orderPlacedDateTime", "numberOfOrderLines", "expirationDate"})
public class OrderHeader {

  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger orderNumber;

  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar orderPlacedDateTime;

  @XmlSchemaType(name = "unsignedInt")
  protected Long numberOfOrderLines;

  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar expirationDate;

  /**
   * Gets the value of the orderNumber property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getOrderNumber() {
    return orderNumber;
  }

  /**
   * Sets the value of the orderNumber property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setOrderNumber(BigInteger value) {
    this.orderNumber = value;
  }

  /**
   * Gets the value of the orderPlacedDateTime property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getOrderPlacedDateTime() {
    return orderPlacedDateTime;
  }

  /**
   * Sets the value of the orderPlacedDateTime property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setOrderPlacedDateTime(XMLGregorianCalendar value) {
    this.orderPlacedDateTime = value;
  }

  /**
   * Gets the value of the numberOfOrderLines property.
   *
   * @return possible object is {@link Long }
   */
  public Long getNumberOfOrderLines() {
    return numberOfOrderLines;
  }

  /**
   * Sets the value of the numberOfOrderLines property.
   *
   * @param value allowed object is {@link Long }
   */
  public void setNumberOfOrderLines(Long value) {
    this.numberOfOrderLines = value;
  }

  /**
   * Gets the value of the expirationDate property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getExpirationDate() {
    return expirationDate;
  }

  /**
   * Sets the value of the expirationDate property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setExpirationDate(XMLGregorianCalendar value) {
    this.expirationDate = value;
  }
}
