//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

@javax.xml.bind.annotation.XmlSchema(
    namespace =
        "http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/",
    elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;
