//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Java class for Package complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Package">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequenceNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="assignmentNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" minOccurs="0"/>
 *         &lt;element name="packageID" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha30" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha40" minOccurs="0"/>
 *         &lt;element name="trackingNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha50" minOccurs="0"/>
 *         &lt;element name="additionalTrackingNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha50" minOccurs="0"/>
 *         &lt;element name="dimensions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Dimensions" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Status" minOccurs="0"/>
 *         &lt;element name="shipDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="weight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Weight" minOccurs="0"/>
 *         &lt;element name="uom" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha20" minOccurs="0"/>
 *         &lt;element name="thirdPartyShippingCost" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Cost" minOccurs="0"/>
 *         &lt;element name="supplierShippingCost" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Cost" minOccurs="0"/>
 *         &lt;element name="asnNumber" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha25" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Package",
    propOrder = {
      "sequenceNumber",
      "assignmentNumber",
      "packageID",
      "type",
      "trackingNumber",
      "additionalTrackingNumber",
      "dimensions",
      "status",
      "shipDate",
      "weight",
      "uom",
      "thirdPartyShippingCost",
      "supplierShippingCost",
      "asnNumber"
    })
@XmlSeeAlso({
  com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload
      .PlaceFulfillmentOrderRequest.MessageBody.CustomerOrderInfo.CustomerOrder.FulfillmentOrders
      .OrderLines.Package.class
})
public class Package {

  @XmlSchemaType(name = "unsignedShort")
  protected Integer sequenceNumber;

  @XmlSchemaType(name = "unsignedLong")
  protected BigInteger assignmentNumber;

  protected String packageID;
  protected String type;
  protected String trackingNumber;
  protected String additionalTrackingNumber;
  protected Dimensions dimensions;
  protected Status status;

  @XmlSchemaType(name = "dateTime")
  protected XMLGregorianCalendar shipDate;

  protected Weight weight;
  protected String uom;
  protected Cost thirdPartyShippingCost;
  protected Cost supplierShippingCost;
  protected String asnNumber;

  /**
   * Gets the value of the sequenceNumber property.
   *
   * @return possible object is {@link Integer }
   */
  public Integer getSequenceNumber() {
    return sequenceNumber;
  }

  /**
   * Sets the value of the sequenceNumber property.
   *
   * @param value allowed object is {@link Integer }
   */
  public void setSequenceNumber(Integer value) {
    this.sequenceNumber = value;
  }

  /**
   * Gets the value of the assignmentNumber property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getAssignmentNumber() {
    return assignmentNumber;
  }

  /**
   * Sets the value of the assignmentNumber property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setAssignmentNumber(BigInteger value) {
    this.assignmentNumber = value;
  }

  /**
   * Gets the value of the packageID property.
   *
   * @return possible object is {@link String }
   */
  public String getPackageID() {
    return packageID;
  }

  /**
   * Sets the value of the packageID property.
   *
   * @param value allowed object is {@link String }
   */
  public void setPackageID(String value) {
    this.packageID = value;
  }

  /**
   * Gets the value of the type property.
   *
   * @return possible object is {@link String }
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   *
   * @param value allowed object is {@link String }
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * Gets the value of the trackingNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getTrackingNumber() {
    return trackingNumber;
  }

  /**
   * Sets the value of the trackingNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setTrackingNumber(String value) {
    this.trackingNumber = value;
  }

  /**
   * Gets the value of the additionalTrackingNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getAdditionalTrackingNumber() {
    return additionalTrackingNumber;
  }

  /**
   * Sets the value of the additionalTrackingNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAdditionalTrackingNumber(String value) {
    this.additionalTrackingNumber = value;
  }

  /**
   * Gets the value of the dimensions property.
   *
   * @return possible object is {@link Dimensions }
   */
  public Dimensions getDimensions() {
    return dimensions;
  }

  /**
   * Sets the value of the dimensions property.
   *
   * @param value allowed object is {@link Dimensions }
   */
  public void setDimensions(Dimensions value) {
    this.dimensions = value;
  }

  /**
   * Gets the value of the status property.
   *
   * @return possible object is {@link Status }
   */
  public Status getStatus() {
    return status;
  }

  /**
   * Sets the value of the status property.
   *
   * @param value allowed object is {@link Status }
   */
  public void setStatus(Status value) {
    this.status = value;
  }

  /**
   * Gets the value of the shipDate property.
   *
   * @return possible object is {@link XMLGregorianCalendar }
   */
  public XMLGregorianCalendar getShipDate() {
    return shipDate;
  }

  /**
   * Sets the value of the shipDate property.
   *
   * @param value allowed object is {@link XMLGregorianCalendar }
   */
  public void setShipDate(XMLGregorianCalendar value) {
    this.shipDate = value;
  }

  /**
   * Gets the value of the weight property.
   *
   * @return possible object is {@link Weight }
   */
  public Weight getWeight() {
    return weight;
  }

  /**
   * Sets the value of the weight property.
   *
   * @param value allowed object is {@link Weight }
   */
  public void setWeight(Weight value) {
    this.weight = value;
  }

  /**
   * Gets the value of the uom property.
   *
   * @return possible object is {@link String }
   */
  public String getUom() {
    return uom;
  }

  /**
   * Sets the value of the uom property.
   *
   * @param value allowed object is {@link String }
   */
  public void setUom(String value) {
    this.uom = value;
  }

  /**
   * Gets the value of the thirdPartyShippingCost property.
   *
   * @return possible object is {@link Cost }
   */
  public Cost getThirdPartyShippingCost() {
    return thirdPartyShippingCost;
  }

  /**
   * Sets the value of the thirdPartyShippingCost property.
   *
   * @param value allowed object is {@link Cost }
   */
  public void setThirdPartyShippingCost(Cost value) {
    this.thirdPartyShippingCost = value;
  }

  /**
   * Gets the value of the supplierShippingCost property.
   *
   * @return possible object is {@link Cost }
   */
  public Cost getSupplierShippingCost() {
    return supplierShippingCost;
  }

  /**
   * Sets the value of the supplierShippingCost property.
   *
   * @param value allowed object is {@link Cost }
   */
  public void setSupplierShippingCost(Cost value) {
    this.supplierShippingCost = value;
  }

  /**
   * Gets the value of the asnNumber property.
   *
   * @return possible object is {@link String }
   */
  public String getAsnNumber() {
    return asnNumber;
  }

  /**
   * Sets the value of the asnNumber property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAsnNumber(String value) {
    this.asnNumber = value;
  }
}
