//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.xmlns.walmartstores.com/Header/datatypes/MessageHeader/1.4/}MessageHeader"/>
 *         &lt;element name="MessageBody">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="responseMessage" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}ResponseMessage"/>
 *                   &lt;element name="MessageExtensions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}MessageExtension" maxOccurs="10" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "",
    propOrder = {"messageHeader", "messageBody"})
@XmlRootElement(name = "PlaceFulfillmentOrderResponse")
public class PlaceFulfillmentOrderResponse {

  @XmlElement(
      name = "MessageHeader",
      namespace = "http://www.xmlns.walmartstores.com/Header/datatypes/MessageHeader/1.4/",
      required = true)
  protected MessageHeader messageHeader;

  @XmlElement(name = "MessageBody", required = true)
  protected PlaceFulfillmentOrderResponse.MessageBody messageBody;

  /**
   * Gets the value of the messageHeader property.
   *
   * @return possible object is {@link MessageHeader }
   */
  public MessageHeader getMessageHeader() {
    return messageHeader;
  }

  /**
   * Sets the value of the messageHeader property.
   *
   * @param value allowed object is {@link MessageHeader }
   */
  public void setMessageHeader(MessageHeader value) {
    this.messageHeader = value;
  }

  /**
   * Gets the value of the messageBody property.
   *
   * @return possible object is {@link PlaceFulfillmentOrderResponse.MessageBody }
   */
  public PlaceFulfillmentOrderResponse.MessageBody getMessageBody() {
    return messageBody;
  }

  /**
   * Sets the value of the messageBody property.
   *
   * @param value allowed object is {@link PlaceFulfillmentOrderResponse.MessageBody }
   */
  public void setMessageBody(PlaceFulfillmentOrderResponse.MessageBody value) {
    this.messageBody = value;
  }

  /**
   * Java class for anonymous complex type.
   *
   * <p>The following schema fragment specifies the expected content contained within this class.
   *
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="responseMessage" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}ResponseMessage"/>
   *         &lt;element name="MessageExtensions" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}MessageExtension" maxOccurs="10" minOccurs="0"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(
      name = "",
      propOrder = {"responseMessage", "messageExtensions"})
  public static class MessageBody {

    @XmlElement(required = true)
    protected ResponseMessage responseMessage;

    @XmlElement(name = "MessageExtensions")
    protected List<MessageExtension> messageExtensions;

    /**
     * Gets the value of the responseMessage property.
     *
     * @return possible object is {@link ResponseMessage }
     */
    public ResponseMessage getResponseMessage() {
      return responseMessage;
    }

    /**
     * Sets the value of the responseMessage property.
     *
     * @param value allowed object is {@link ResponseMessage }
     */
    public void setResponseMessage(ResponseMessage value) {
      this.responseMessage = value;
    }

    /**
     * Gets the value of the messageExtensions property.
     *
     * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
     * modification you make to the returned list will be present inside the JAXB object. This is
     * why there is not a <CODE>set</CODE> method for the messageExtensions property.
     *
     * <p>For example, to add a new item, do as follows:
     *
     * <pre>
     *    getMessageExtensions().add(newItem);
     * </pre>
     *
     * <p>Objects of the following type(s) are allowed in the list {@link MessageExtension }
     */
    public List<MessageExtension> getMessageExtensions() {
      if (messageExtensions == null) {
        messageExtensions = new ArrayList<>();
      }
      return this.messageExtensions;
    }

    public void setMessageExtensions(List<MessageExtension> value) {
      this.messageExtensions = null;
      List<MessageExtension> draftl = this.getMessageExtensions();
      draftl.addAll(value);
    }
  }
}
