//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Product complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Product">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Offering">
 *       &lt;sequence>
 *         &lt;element name="isAvailableForPickup" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="weight" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Weight" minOccurs="0"/>
 *         &lt;element name="isMultiBox" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isSoldByWeight" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Product",
    propOrder = {"isAvailableForPickup", "weight", "isMultiBox", "isSoldByWeight"})
public class Product extends Offering {

  protected Boolean isAvailableForPickup;
  protected Weight weight;
  protected Boolean isMultiBox;
  protected Boolean isSoldByWeight;

  /**
   * Gets the value of the isAvailableForPickup property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsAvailableForPickup() {
    return isAvailableForPickup;
  }

  /**
   * Sets the value of the isAvailableForPickup property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsAvailableForPickup(Boolean value) {
    this.isAvailableForPickup = value;
  }

  /**
   * Gets the value of the weight property.
   *
   * @return possible object is {@link Weight }
   */
  public Weight getWeight() {
    return weight;
  }

  /**
   * Sets the value of the weight property.
   *
   * @param value allowed object is {@link Weight }
   */
  public void setWeight(Weight value) {
    this.weight = value;
  }

  /**
   * Gets the value of the isMultiBox property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsMultiBox() {
    return isMultiBox;
  }

  /**
   * Sets the value of the isMultiBox property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsMultiBox(Boolean value) {
    this.isMultiBox = value;
  }

  /**
   * Gets the value of the isSoldByWeight property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isIsSoldByWeight() {
    return isSoldByWeight;
  }

  /**
   * Sets the value of the isSoldByWeight property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setIsSoldByWeight(Boolean value) {
    this.isSoldByWeight = value;
  }
}
