//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ReturnDetails complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ReturnDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="returnCode" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha2" minOccurs="0"/>
 *         &lt;element name="returnPermit" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}ReturnPermit" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ReturnDetails",
    propOrder = {"returnCode", "returnPermit"})
public class ReturnDetails {

  protected String returnCode;
  protected ReturnPermit returnPermit;

  /**
   * Gets the value of the returnCode property.
   *
   * @return possible object is {@link String }
   */
  public String getReturnCode() {
    return returnCode;
  }

  /**
   * Sets the value of the returnCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setReturnCode(String value) {
    this.returnCode = value;
  }

  /**
   * Gets the value of the returnPermit property.
   *
   * @return possible object is {@link ReturnPermit }
   */
  public ReturnPermit getReturnPermit() {
    return returnPermit;
  }

  /**
   * Sets the value of the returnPermit property.
   *
   * @param value allowed object is {@link ReturnPermit }
   */
  public void setReturnPermit(ReturnPermit value) {
    this.returnPermit = value;
  }
}
