//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for ValueAddedService complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ValueAddedService">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sequenceNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" minOccurs="0"/>
 *         &lt;element name="code" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha3" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha512" minOccurs="0"/>
 *         &lt;element name="vASData" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}VASData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fee" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Fee" minOccurs="0"/>
 *         &lt;element name="cost" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}Cost" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ValueAddedService",
    propOrder = {"sequenceNumber", "code", "description", "vasData", "fee", "cost"})
public class ValueAddedService {

  @XmlSchemaType(name = "unsignedInt")
  protected Long sequenceNumber;

  protected String code;
  protected String description;

  @XmlElement(name = "vASData")
  protected List<VASData> vasData;

  protected Fee fee;
  protected Cost cost;

  /**
   * Gets the value of the sequenceNumber property.
   *
   * @return possible object is {@link Long }
   */
  public Long getSequenceNumber() {
    return sequenceNumber;
  }

  /**
   * Sets the value of the sequenceNumber property.
   *
   * @param value allowed object is {@link Long }
   */
  public void setSequenceNumber(Long value) {
    this.sequenceNumber = value;
  }

  /**
   * Gets the value of the code property.
   *
   * @return possible object is {@link String }
   */
  public String getCode() {
    return code;
  }

  /**
   * Sets the value of the code property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCode(String value) {
    this.code = value;
  }

  /**
   * Gets the value of the description property.
   *
   * @return possible object is {@link String }
   */
  public String getDescription() {
    return description;
  }

  /**
   * Sets the value of the description property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDescription(String value) {
    this.description = value;
  }

  /**
   * Gets the value of the vasData property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the vasData property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getVASData().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link VASData }
   */
  public List<VASData> getVASData() {
    if (vasData == null) {
      vasData = new ArrayList<>();
    }
    return this.vasData;
  }

  /**
   * Gets the value of the fee property.
   *
   * @return possible object is {@link Fee }
   */
  public Fee getFee() {
    return fee;
  }

  /**
   * Sets the value of the fee property.
   *
   * @param value allowed object is {@link Fee }
   */
  public void setFee(Fee value) {
    this.fee = value;
  }

  /**
   * Gets the value of the cost property.
   *
   * @return possible object is {@link Cost }
   */
  public Cost getCost() {
    return cost;
  }

  /**
   * Sets the value of the cost property.
   *
   * @param value allowed object is {@link Cost }
   */
  public void setCost(Cost value) {
    this.cost = value;
  }

  public void setVASData(List<VASData> value) {
    this.vasData = null;
    List<VASData> draftl = this.getVASData();
    draftl.addAll(value);
  }
}
