//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.08.30 at 08:54:50 PM PDT
//

package com.walmart.fms.infrastructure.integration.gateway.store.dto.orderdownload;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for Vehicle complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Vehicle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}unsignedShort" minOccurs="0"/>
 *         &lt;element name="make" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *         &lt;element name="model" type="{http://www.xmlns.walmartstores.com/SupplyChain/FulfillmentManagement/datatypes/PlaceFulfillmentOrder/}alpha255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "Vehicle",
    propOrder = {"year", "make", "model"})
public class Vehicle {

  @XmlSchemaType(name = "unsignedShort")
  protected Integer year;

  protected String make;
  protected String model;

  /**
   * Gets the value of the year property.
   *
   * @return possible object is {@link Integer }
   */
  public Integer getYear() {
    return year;
  }

  /**
   * Sets the value of the year property.
   *
   * @param value allowed object is {@link Integer }
   */
  public void setYear(Integer value) {
    this.year = value;
  }

  /**
   * Gets the value of the make property.
   *
   * @return possible object is {@link String }
   */
  public String getMake() {
    return make;
  }

  /**
   * Sets the value of the make property.
   *
   * @param value allowed object is {@link String }
   */
  public void setMake(String value) {
    this.make = value;
  }

  /**
   * Gets the value of the model property.
   *
   * @return possible object is {@link String }
   */
  public String getModel() {
    return model;
  }

  /**
   * Sets the value of the model property.
   *
   * @param value allowed object is {@link String }
   */
  public void setModel(String value) {
    this.model = value;
  }
}
