{
 "title": "ASDA order management Application Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values({mms_source=\"non-wcnp\",product_id=\"824\"},application)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Vendor based OPM ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uber Eats  - OPM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(uber_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\",type=\"uber_accept_order\"}[1m])*60)",
     "legendFormat": "OPM Metrics "
    }
   ]
  },
  {
   "title": "JustEat  - OPM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(just_eats_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\",type=\"just_eats_accept_order\"}[1m])*60)",
     "legendFormat": "JustEat OPM Metrics "
    }
   ]
  },
  {
   "title": "Primary and Secondary Port Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Primary Port Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(api) (rate(primary_port_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))\n",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Secondary Port API Requests/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(methodName) (rate(secondary_port_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))\n",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Primary port exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(primary_port_exception_counter_total{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Secondary port exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(pysipyp_exception_total{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "PYSIPYP "
    },
    {
     "expr": "topk(100, sum by(type) (rate(tax_exception_total{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "Tax Service "
    },
    {
     "expr": "topk(100, sum by(type) (rate(iro_exception_total{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "IRO"
    }
   ]
  },
  {
   "title": "Primary Port Avg Response times in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum by(api) (rate(primary_port_invocation_seconds_sum{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])) / sum by(api) (rate(primary_port_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m]))) * 1000",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "Secondary Port API Avg Response Times in ms",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(methodName) (rate(secondary_port_invocation_seconds_sum{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])) / sum by(methodName) (rate(secondary_port_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])) * 1000\n",
     "legendFormat": "{{methodName}}"
    }
   ]
  },
  {
   "title": "Primary Port Http Statuses/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(status) (rate(primary_port_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\",isSuccess=\"false\"}[1m])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Secondary Port Http Statuses/sec",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(status) (rate(secondary_port_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\",isSuccess=\"false\"}[1m])))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Inbount Order CountBy Domain/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(inbound_order_count_total{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Oms Order Creation exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(oms_inbound_exception_counter_total{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Fms Order Creation Exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(fms_inbound_exception_counter_total{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Uber APIs Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Uber API Requests/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(uber_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Uber API Average Response Times in ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (rate(uber_invocation_seconds_sum{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])) / sum by(type) (rate(uber_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])) * 1000\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Uber API Exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(uber_exception_total{application=\"order-management-system-app\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Uber Web hook Exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(uber_web_hook_exception_total{application=\"order-management-system-app\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "JustEat API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "JustEat API Requests/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(just_eats_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "JustEat API Average Response Times in ms",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(type) (rate(just_eats_invocation_seconds_sum{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])) / sum by(type) (rate(just_eats_invocation_seconds_count{application=\"$application\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])) * 1000\n",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "JustEat API Exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(just_eats_exception_total{application=\"order-management-system-app\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "JustEat Web hook Exceptions/sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(100, sum by(type) (rate(just_eat_web_hook_exception_total{application=\"order-management-system-app\",mms_source=\"non-wcnp\",product_id=\"824\"}[1m])))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}