{
 "title": "ASDA order management Resilience4j Metrics",
 "description": "Resilience4j Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": "label_values({mms_source=\"non-wcnp\",product_id=\"824\"},application)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(resilience4j_circuitbreaker_state{application=\"$application\"}, instance)"
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": "label_values(resilience4j_circuitbreaker_state{application=\"$application\"}, name)"
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": "label_values(resilience4j_retry_calls_total{application=\"$application\"}, name)"
   },
   {
    "name": "bulkhead_name",
    "label": "Bulkead Name",
    "query": "label_values(resilience4j_bulkhead_available_concurrent_calls{application=\"$application\"}, name)"
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", instance=\"$instance\",state=\"closed\"})"
    }
   ]
  },
  {
   "title": "Number of open CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", instance=\"$instance\",state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{application=\"$application\", instance=\"$instance\"}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", instance=\"$instance\",state=\"half_open\"})"
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "circuitbreaker_name" },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{mms_source=\"non-wcnp\",product_id=\"824\",application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 44 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{mms_source=\"non-wcnp\",product_id=\"824\",application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 51 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 66 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 74 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{mms_source=\"non-wcnp\",product_id=\"824\",application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 74 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 81 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 89 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 96 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 104 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{mms_source=\"non-wcnp\",product_id=\"824\",application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 104 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 111 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 119 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 126 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 134 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{mms_source=\"non-wcnp\",product_id=\"824\",application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 134 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 141 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 149 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 156 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 163 } },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 164 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{mms_source=\"non-wcnp\",product_id=\"824\",application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 164 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 171 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 179 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 186 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 193 } },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 194 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{mms_source=\"non-wcnp\",product_id=\"824\",application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 194 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 201 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Call duration percentiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 209 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.98, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "98th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(resilience4j_circuitbreaker_calls_seconds_bucket{application=\"$application\", instance=\"$instance\", name=\"$circuitbreaker_name\"}[1m])) by (le))",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 216 },
   "yaxes": [
    { "format": "s", "label": "Average duration" }
   ],
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", instance=\"$instance\",name=\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 223 }, "repeat": "retry_name" },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 224 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total{application=\"$application\",instance=\"$instance\",name=\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 } },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 233 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total{application=\"$application\",instance=\"$instance\",name=\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 241 } },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total{application=\"$application\",instance=\"$instance\",name=\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 250 } },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 251 },
   "yaxes": [
    { "format": "short", "label": "Number of calls" }
   ],
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total{application=\"$application\",instance=\"$instance\",name=\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 259 }, "repeat": "bulkhead_name" },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 260 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 268 } },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 269 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 277 } },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 278 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 286 } },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 295 } },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 296 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 304 } },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 305 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=\"$application\",instance=\"$instance\",name=\"$bulkhead_name\"}",
     "legendFormat": "Max allowed Calls"
    }
   ]
  }
 ]
}