package com.walmart.common.domain.type;

import lombok.Getter;

@Getter
public enum DomainEventType {
  OMS_ORDER_CANCELLED("OMS_ORDER_CANCELLED"),
  FMS_ORDER_DELIVERED("FMS_ORDER_DELIVERED"),
  FMS_ORDER_PICK_COMPLETE("FMS_ORDER_PICK_COMPLETE"),
  FMS_ORDER_CONFIRM("FMS_ORDER_CONFIRM"),
  FMS_ORDER_CANCELLED("FMS_ORDER_CANCELLED"),
  OMS_ORDER_CREATED("OMS_ORDER_CREATED"),
  OMS_ORDER_PICK_COMPLETE("OMS_ORDER_PICK_COMPLETE"),
  OMS_ORDER_DELIVERED("OMS_ORDER_DELIVERED"),
  OMS_ORDER_CONFIRM("OMS_ORDER_CONFIRM"),
  FMS_ORDER_PICK_STARTED("FMS_ORDER_PICK_STARTED"),
  MARKET_PLACE_ORDER_CREATED("MARKET_PLACE_ORDER_CREATED"),
  MARKET_PLACE_ORDER_CANCELLED("MARKET_PLACE_ORDER_CANCELLED"),
  OMS_ORDER_UPDATED("OMS_ORDER_UPDATED");

  private final String name;

  DomainEventType(String name) {
    this.name = name;
  }

}
