CREATE DATABASE OMSCORE
GO

USE OMSCORE;

CREATE SCHEMA OMSCORE;

CREATE TABLE OMSCORE.MARKET_PLACE_EVENTS (
RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CREATED_DATE datetime2(7) NULL,
MODIFIED_DATE datetime2(7) NULL,
DB_LOCK_VERSION bigint NULL,
EVENT_TYPE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
EXTERNAL_ORDER_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
RESOURCE_URL varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
SOURCE_EVENT_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
VENDOR varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
CONSTRAINT MARKET_PLACE_EVENT_PK PRIMARY KEY (RECORD_ID)
)
GO

CREATE TABLE OMSCORE.MARKET_PLACE_ORDER (
RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CREATED_DATE datetime2(7) NULL,
MODIFIED_DATE datetime2(7) NULL,
DB_LOCK_VERSION bigint NULL,
FIRST_NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
LAST_NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ORDER_DUE_TIME datetime2(7) NULL,
ORDER_STATUS varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
SOURCE_MODIFIED_DATE datetime2(7) NULL,
STORE_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
VENDOR_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
VENDOR_ORDER_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
CONSTRAINT MARKET_PLACE_ORDER_PK PRIMARY KEY (RECORD_ID)
) GO

CREATE TABLE OMSCORE.MARKETPLACE_ITEM (
RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CREATED_DATE datetime2(7) NULL,
MODIFIED_DATE datetime2(7) NULL,
DB_LOCK_VERSION bigint NULL,
EXTERNAL_ITEM_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ITEM_DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ITEM_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ITEM_TYPE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
VENDOR_INSTANCE_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
BASE_TOTAL_PRICE float NULL,
BASE_UNIT_PRICE float NULL,
TOTAL_PRICE float NULL,
UNIT_PRICE float NULL,
QUANTITY bigint NULL,
ORDER_RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT MARKET_PACE_ITEM_PK PRIMARY KEY (RECORD_ID),
CONSTRAINT MARKETPLACE_ITEM_FK1 FOREIGN KEY (ORDER_RECORD_ID) REFERENCES OMSCORE.MARKET_PLACE_ORDER(RECORD_ID)
) GO

CREATE TABLE OMSCORE.OMS_ORDER (
RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CREATED_DATE datetime2(7) NULL,
MODIFIED_DATE datetime2(7) NULL,
DB_LOCK_VERSION bigint NULL,
AUTH_STATUS varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
DELIVERY_DATE datetime2(7) NULL,
FULFILLMENT_TYPE int NULL,
VENDOR varchar(255) NULL,
VENDOR_ORDER_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ORDER_STATUS varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PICKUP_LOCATION_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
CARRIER_BAG_CHARGE float NULL,
DELIVERY_CHARGE float NULL,
ORDER_SUB_TOTAL float NULL,
ORDER_TOTAL float NULL,
POS_TOTAL float NULL,
SOURCE_ORDER_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
SPOKE_STORE_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
STORE_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
TENANT_ID varchar(255) NULL,
transientState bit NOT NULL,
VERTICAL_ID varchar(255) NULL,
CONSTRAINT PK__OMS_ORDE__E2DA602F3E4C8F85 PRIMARY KEY (RECORD_ID)
) GO

CREATE TABLE OMSCORE.OMS_ORDER_ITEM(
                                       RECORD_ID          UNIQUEIDENTIFIER                                  NOT NULL,
                                       CREATED_DATE       datetime2(7)                                      NULL,
                                       MODIFIED_DATE      datetime2(7)                                      NULL,
                                       DB_LOCK_VERSION    bigint                                            NULL,
                                       CATALOG_INFO       nvarchar(4000)                                   NULL,
                                       CONSUMER_ITEM_NUM  varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                       ITEM_DESCRIPTION   varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                       UNIT_PRICE         numeric(19, 2)                                    NULL,
                                       VENDOR_TOTAL_PRICE numeric(19, 2)                                    NULL,
                                       VENDOR_UNIT_PRICE  numeric(19, 2)                                    NULL,
                                       QUANTITY           bigint                                            NULL,
                                       SALES_UNIT         varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                       SKU_ID             varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                       UOM                varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
                                       WEIGHT             float                                             NULL,
ORDER_RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT PK__OMS_ORDE__E2DA602F0A21FD13 PRIMARY KEY (RECORD_ID),
CONSTRAINT FKl2nwlw69bvi02aq4pkhi7ywes FOREIGN KEY (ORDER_RECORD_ID) REFERENCES OMSCORE.OMS_ORDER(RECORD_ID)
) GO


CREATE TABLE OMSCORE.OMS_CUSTOMER_CONTACT_INFO (
RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CREATED_DATE datetime2(7) NULL,
MODIFIED_DATE datetime2(7) NULL,
DB_LOCK_VERSION bigint NULL,
email varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
FIRST_NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
LAST_NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
MIDDLE_NAME varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
TITLE varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
mobile_number varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
phone_number_one varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
phone_number_two varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ORDER_RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT PK__OMS_CUST__E2DA602FCBB9FED5 PRIMARY KEY (RECORD_ID),
CONSTRAINT FK36ieq415todnq9jk5cyfe8b8q FOREIGN KEY (ORDER_RECORD_ID) REFERENCES OMSCORE.OMS_ORDER(RECORD_ID)
) GO


CREATE TABLE OMSCORE.OMS_PICKED_ITEM (
RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CREATED_DATE datetime2(7) NULL,
MODIFIED_DATE datetime2(7) NULL,
DB_LOCK_VERSION bigint NULL,
DEPARTMENT_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ORDERED_CIN varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PICKED_ITEM_DESCRIPTION varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
ADJUSTED_PRICE numeric(19,2) NULL,
ADJUSTED_PRICE_EX_VAT numeric(19,2) NULL,
DISPLAY_PRICE numeric(19,2) NULL,
UNIT_PRICE numeric(19,2) NULL,
VAT_AMOUNT numeric(19,2) NULL,
WEB_ADJUSTED_PRICE numeric(19,2) NULL,
PICKED_BY varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
QUANTITY bigint NULL,
WEIGHT float NULL,
ORDER_ITEM_RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT PK__OMS_PICK__E2DA602FC54A5266 PRIMARY KEY (RECORD_ID),
CONSTRAINT FK_OMS_PICK_ITEM_FK1 FOREIGN KEY (ORDER_ITEM_RECORD_ID) REFERENCES OMSCORE.OMS_ORDER_ITEM(RECORD_ID)
) GO

CREATE TABLE OMSCORE.OMS_PICKED_ITEM_UPC (
RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CREATED_DATE datetime2(7) NULL,
MODIFIED_DATE datetime2(7) NULL,
DB_LOCK_VERSION bigint NULL,
QUANTITY bigint NULL,
STORE_UNIT_PRICE numeric(19,2) NULL,
UOM varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
UPC varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
WEIGHT float NULL,
WALMART_ITEM_NUM varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
PICKED_ITEM_RECORD_ID UNIQUEIDENTIFIER NOT NULL,
CONSTRAINT PK__OMS_PICK__E2DA602F95C1BB2C PRIMARY KEY (RECORD_ID),
CONSTRAINT FKjoxuf3pju0jxm7yp22ou6utfr FOREIGN KEY (PICKED_ITEM_RECORD_ID) REFERENCES OMSCORE.OMS_PICKED_ITEM(RECORD_ID)
) GO



---FMS Tables Begin----

CREATE TABLE OMSCORE.FULFILLMENT_ORDER (
    RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
    CREATED_DATE datetime2(7) NULL,
    MODIFIED_DATE datetime2(7) NULL,
    DB_LOCK_VERSION bigint NULL,
    TENANT_ID varchar(30) NULL,
    VERTICAL_ID varchar(30) NULL,
    VENDOR varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
    VENDOR_ORDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS   NULL,
    SOURCE_ORDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
    STORE_ORDER_ID varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS  NOT NULL,
    STORE_ID varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    PICKUP_LOCATION_ID varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    DELIVERY_DATE datetime2(7) NULL,
    FULFILLMENT_ORDER_STATUS varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    ORDER_STATUS varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    AUTH_STATUS varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    WEB_ORDER_TOTAL float NULL,
    POS_TOTAL float NULL,
    ORDER_VAT_AMOUNT float NULL,
    DELIVERY_INSTRUCTION varchar(1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CANCELLED_REASON_CODE varchar(30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CANCELLED_BY varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT FULFILLMENT_ORDER_PK PRIMARY KEY (RECORD_ID)
);
 GO


CREATE TABLE OMSCORE.FULFILLMENT_ORDER_LINE (
	RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
	DB_LOCK_VERSION bigint NULL,
    ITEM_ID  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSUMER_ITEM_NUMBER  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	PICKER_ITEM_DESCRIPTION  varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	QUANTITY bigint NULL,
	WEIGHT float NULL,
	UNIT_PRICE float NULL,
	TEMPERATURE_ZONE  varchar(200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNIT_OF_MEASUREMENT  varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	SALES_UNIT varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	IMAGE_URL varchar(254) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	MIN_IDEAL_DAY_VALUE bigint NULL,
	MAX_IDEAL_DAY_VALUE bigint NULL,
	IS_SELLBY_DATE_REQUIRED bit NULL,
	UPC_INFO NVARCHAR(300) NULL,
	ORDER_RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CONSTRAINT FULFILLMENT_ORDER_LINE_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT FULFILLMENT_ORDER_LINE_FK1 FOREIGN KEY (ORDER_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER(RECORD_ID)
);
GO

CREATE TABLE OMSCORE.FULFILLMENT_ORDER_LINE_UPC (
	RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
	DB_LOCK_VERSION bigint NULL,
	UPC  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REF_RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CONSTRAINT FULFILLMENT_ORDER_LINE_UPC_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT FULFILLMENT_ORDER_LINE_UPC_FK1 FOREIGN KEY (REF_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER_LINE(RECORD_ID)
);
GO

CREATE TABLE OMSCORE.FULFILLMENT_ORDER_PICKED_LINE (
	RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
    DB_LOCK_VERSION bigint NULL,
	CONSUMER_ITEM_NUMBER  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	WALMART_ITEM_NUMBER  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	DESCRIPTION  varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	QUANTITY bigint NULL,
	WEIGHT float NULL,
	UNIT_PRICE float NULL,
    ADJUSTED_PRICE float NULL,
    ADJ_PRICE_EX_VAT float NULL,
    WEB_ADJUSTED_PRICE float NULL,
    VAT_AMOUNT float NULL,
	DEPARTMENT_ID  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	PICKED_BY  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	SELL_BY_DATE datetime2(7) NULL,
	ORDERED_ITEM_RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CONSTRAINT FULFILLMENT_ORDER_PICKED_LINE_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT FULFILLMENT_ORDER_PICKED_LINE_FK1 FOREIGN KEY (ORDERED_ITEM_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER_LINE(RECORD_ID)
);
GO


CREATE TABLE OMSCORE.FULFILLMENT_ORDER_PICK_LINE_UPC (
	RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
    DB_LOCK_VERSION bigint NULL,
	UPC  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	WALMART_ITEM_NUMBER  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	UNIT_OF_MEASUREMENT  varchar(2) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
    QUANTITY bigint NULL,
    WEIGHT float NULL,
    STORE_UNIT_PRICE float NULL,
	REF_RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CONSTRAINT FULFILLMENT_ORDER_PICK_LINE_UPC_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT FULFILLMENT_ORDER_PICK_LINE_UPC_FK1 FOREIGN KEY (REF_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER_PICKED_LINE(RECORD_ID)
);
GO


CREATE TABLE OMSCORE.FULFILLMENT_ORDER_SCHEDULING_INFO (
	RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
    DB_LOCK_VERSION bigint NULL,
	TRIP_ID  varchar(80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	VAN_ID  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS  NULL,
	DOOR_STEP_TIME  bigint NULL ,
	SLOT_START_TIME  datetime2(7) NULL,
	SLOT_END_TIME  datetime2(7) NULL,
	ORDER_DUE_TIME datetime2(7) NULL,
    SCHEDULE_NUMBER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    LOAD_NUMBER varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REF_RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CONSTRAINT FULFILLMENT_ORDER_SCHEDULING_INFO_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT FULFILLMENT_ORDER_SCHEDULING_INFO_FK1 FOREIGN KEY (REF_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER(RECORD_ID)
);
GO

CREATE TABLE OMSCORE.FULFILLMENT_ORDER_ADDRESS (
	RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
    DB_LOCK_VERSION bigint NULL,
	ADDRESS_TYPE  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ADDRESS_ONE  varchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ADDRESS_TWO  varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ADDRESS_THREE  varchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CITY  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUNTY  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	STATE  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	POSTAL_CODE  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	COUNTRY  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LATITUDE  varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LONGITUDE  varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	REF_RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CONSTRAINT FULFILLMENT_ORDER_ADDRESS_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT FULFILLMENT_ORDER_ADDRESS_FK1 FOREIGN KEY (REF_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER(RECORD_ID)
);
GO


CREATE TABLE OMSCORE.FULFILLMENT_ORDER_CONTACT_INFO (
	RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
    DB_LOCK_VERSION bigint NULL,
	CUSTOMER_ID  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	TITLE  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	FIRST_NAME  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MIDDLE_NAME  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	LAST_NAME  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	EMAIL  varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PHONE_NUMBER_ONE  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	PHONE_NUMBER_TWO  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	MOBILE_NUMBER  varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ORDER_RECORD_ID UNIQUEIDENTIFIER   NOT NULL,
	CONSTRAINT FULFILLMENT_ORDER_CONTACT_INFO_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT FULFILLMENT_ORDER_CONTACT_INFO_FK1 FOREIGN KEY (ORDER_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER(RECORD_ID)
);
GO


CREATE TABLE OMSCORE.FULFILLMENT_ORDER_TIMESTAMPS (
                                                      RECORD_ID            UNIQUEIDENTIFIER NOT NULL,
                                                      CREATED_DATE         datetime2(7)     NULL,
                                                      MODIFIED_DATE        datetime2(7)     NULL,
                                                      DB_LOCK_VERSION      bigint           NULL,
                                                      PICKING_START_TIME   datetime2(7)     NULL,
                                                      CANCELLED_TIME       datetime2(7)     NULL,
                                                      PICK_COMPLETE_TIME   datetime2(7)     NULL,
                                                      SHIP_CONFIRM_TIME    datetime2(7)     NULL,
                                                      ORDER_DELIVERED_TIME datetime2(7)     NULL,
                                                      PICK_UP_READY_TIME   datetime2(7)     NULL,
                                                      PICK_UP_TIME         datetime2(7)     NULL,
                                                      REF_RECORD_ID        UNIQUEIDENTIFIER NOT NULL,
                                                      CONSTRAINT FULFILLMENT_ORDER_TIMESTAMPS_PK PRIMARY KEY (RECORD_ID),
                                                      CONSTRAINT FULFILLMENT_ORDER_TIMESTAMPS_FK1 FOREIGN KEY (REF_RECORD_ID) REFERENCES OMSCORE.FULFILLMENT_ORDER (RECORD_ID)
);
GO

---FMS Tables End----

--- MarketPlace Indexes Start----

CREATE INDEX IX_MPITEM_ORDRECID ON OMSCORE.MARKETPLACE_ITEM (ORDER_RECORD_ID)
GO

CREATE INDEX IX_MPORD_STORE_ORDSTATUS_DUETIME ON OMSCORE.MARKET_PLACE_ORDER (STORE_ID, ORDER_STATUS, ORDER_DUE_TIME)
GO

CREATE UNIQUE INDEX IX_MPORD_VNDRORDID ON OMSCORE.MARKET_PLACE_ORDER (VENDOR_ORDER_ID)
GO

CREATE UNIQUE INDEX IX_MPEVENTS_SRCEVENTID ON OMSCORE.MARKET_PLACE_EVENTS (SOURCE_EVENT_ID)
GO
--- MarketPlace Indexes End----


-- OMS Indexes Start ---
CREATE UNIQUE INDEX IX_OMSORD_TNT_VERT_VNDRORDID ON OMSCORE.OMS_ORDER (TENANT_ID, VERTICAL_ID, VENDOR_ORDER_ID)
GO

CREATE UNIQUE INDEX IX_OMSORD_TNT_VERT_SRCORDID ON OMSCORE.OMS_ORDER (TENANT_ID, VERTICAL_ID, SOURCE_ORDER_ID)
GO


CREATE INDEX IX_OMSORDITEM_ORDRECID ON OMSCORE.OMS_ORDER_ITEM (ORDER_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_OMSPICKITEM_ITEMRECID ON OMSCORE.OMS_PICKED_ITEM (ORDER_ITEM_RECORD_ID)
GO

CREATE INDEX IX_OMSPICKITEMUPC_PICKITEMRECID ON OMSCORE.OMS_PICKED_ITEM_UPC (PICKED_ITEM_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_OMSORDCONTACT_ORDRECID ON OMSCORE.OMS_CUSTOMER_CONTACT_INFO (ORDER_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_OMSORDSCHED_ORDRECID ON OMSCORE.OMS_ORDER_SCHEDULING_INFO (ORDER_RECORD_ID)
GO

CREATE INDEX IX_OMSORDADDR_ORDRECID ON OMSCORE.OMS_ORDER_ADDRESS_INFO (ORDER_RECORD_ID)
GO

--- OMS Indexes End ---

--- FMS Indexes Start ---
CREATE UNIQUE INDEX IX_FMSORD_TNT_VERT_VNDRORDID ON OMSCORE.FULFILLMENT_ORDER (TENANT_ID, VERTICAL_ID, VENDOR_ORDER_ID)
GO

CREATE UNIQUE INDEX IX_FMSORD_STOREORDID ON OMSCORE.FULFILLMENT_ORDER (STORE_ORDER_ID)
GO


CREATE INDEX IX_FMSORDLINE_ORDRECID ON OMSCORE.FULFILLMENT_ORDER_LINE (ORDER_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_FMSORDPICKLINE_ITEMRECID ON OMSCORE.FULFILLMENT_ORDER_PICKED_LINE (ORDERED_ITEM_RECORD_ID)
GO

CREATE INDEX IX_FMSORDPICKUPC_REFRECID ON OMSCORE.FULFILLMENT_ORDER_PICK_LINE_UPC (REF_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_FMSORDSCHED_REFRECID ON OMSCORE.FULFILLMENT_ORDER_SCHEDULING_INFO (REF_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_FMSORDADDR_REFRECID ON OMSCORE.FULFILLMENT_ORDER_ADDRESS (REF_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_FMSORDCONTACT_ORDRECID ON OMSCORE.FULFILLMENT_ORDER_CONTACT_INFO (ORDER_RECORD_ID)
GO

CREATE UNIQUE INDEX IX_FMSORDTIMESTMP_REFRECID ON OMSCORE.FULFILLMENT_ORDER_TIMESTAMPS (REF_RECORD_ID)
GO
--- FMS Indexes End----

--- AuDit Tables-----
create table OMSCORE.EGRESS_EVENTS
(
    RECORD_ID         uniqueidentifier not null
        constraint EGRESS_EVENTS_PK
            primary key,
    CREATED_DATE      datetime2        null,
    MODIFIED_DATE     datetime2        null,
    DB_LOCK_VERSION   bigint           null,
    SOURCE_DOMAIN     varchar(40) not null,
    EVENT_NAME        varchar(40) not null,
    EVENT_DESCRIPTION varchar(1000) null,
    MESSAGE           varchar(max) not null,
    MESSAGE_FORMAT    varchar(40) null,
    EVENT_STATUS      varchar(40) null,
    RETRIES           int,
    JUST_AUDIT        bit,
    DOMAIN_MODEL_ID   varchar(40) not null
)
go
