CREATE TABLE OMSCORE.OMSCORE.MARKETPLACE_BUNDLED_ITEM (
	RECORD_ID uniqueidentifier NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
	DB_LOCK_VERSION bigint NULL,
	BUNDLE_QUANTITY bigint NULL,
	BUNDLE_SKU_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ITEM_RECORD_ID uniqueidentifier NOT NULL,
	BUNDLE_INSTANCE_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT MARKETPLACE_BUNDLED_ITEM_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT MARKETPLACE_BUNDLED_ITEM_FK1 FOREIGN KEY (ITEM_RECORD_ID) REFERENCES OMSCORE.OMSCORE.MARKETPLACE_ITEM(RECORD_ID) ON DELETE CASCADE
);

CREATE TABLE OMSCORE.OMSCORE.OMS_ORDER_BUNDLED_ITEM (
	RECORD_ID uniqueidentifier NOT NULL,
	CREATED_DATE datetime2(7) NULL,
	MODIFIED_DATE datetime2(7) NULL,
	DB_LOCK_VERSION bigint NULL,
	BUNDLE_QUANTITY bigint NULL,
	BUNDLE_SKU_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	ITEM_RECORD_ID uniqueidentifier NOT NULL,
	BUNDLE_INSTANCE_ID varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	CONSTRAINT OMS_ORDER_BUNDLED_ITEM_PK PRIMARY KEY (RECORD_ID),
	CONSTRAINT OMS_ORDER_BUNDLED_ITEM_FK1 FOREIGN KEY (ITEM_RECORD_ID) REFERENCES OMSCORE.OMSCORE.OMS_ORDER_ITEM(RECORD_ID) ON DELETE CASCADE
);